// ─── Contact Data Vendor Evaluation ───────────────────────────────────────────
// Source: Notion questionnaire, Granola meeting notes, Gmail, Google Calendar
// Tracks phone and email enrichment vendors being evaluated for trial

export type ContactVendorType = "phone" | "email" | "both"

export type ContactVendorStatus =
  | "not-started"       // haven't reached out yet
  | "contacted"         // reached out; waiting on response / signed up self-serve
  | "meeting-booked"    // meeting on calendar (upcoming)
  | "trial-active"      // have API key, actively testing
  | "evaluating"        // call done; in evaluation/comparison
  | "shortlisted"       // made the shortlist post-eval
  | "pass"              // decided not to proceed
  | "already-evaluated" // previously evaluated, not in current cycle

export type QuestionnaireStatus = "not-sent" | "sent" | "in-progress" | "complete"

export interface ContactVendor {
  id: string
  name: string
  type: ContactVendorType
  status: ContactVendorStatus
  slackChannel?: string          // Slack channel URL or #name
  meetingBooked: boolean
  meetingDate?: string           // ISO date or human-readable
  questionnaireStatus: QuestionnaireStatus
  questionnaireUrl?: string      // link to eval questionnaire Google Doc
  hasApiKey: boolean
  trialCredits: number | null    // number of free trial credits
  trialCreditsEquiv?: string     // human-readable equiv, e.g. "~500 phone lookups"
  pricingNotes: string           // pricing summary
  rateLimit?: string             // e.g. "100 req/min"
  latencyEstimateMs?: number | null  // rough p50 latency estimate if known
  notes: string
  contacts?: string[]
  website?: string
}

export const contactVendors: ContactVendor[] = [

  // ── Phone + Email vendors ───────────────────────────────────────────────────

  {
    id: "bytemine",
    name: "Bytemine",
    type: "both",
    status: "not-started",
    meetingBooked: false,
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: null,
    pricingNotes: "",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "On priority eval list. Not yet contacted.",
    website: "bytemine.io",
  },

  {
    id: "crustdata",
    name: "CrustData",
    type: "both",
    status: "not-started",
    meetingBooked: false,
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: null,
    pricingNotes: "",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "On priority eval list. Not yet contacted.",
    website: "crustdata.com",
  },

  {
    id: "enrichcrm",
    name: "EnrichCRM",
    type: "both",
    status: "not-started",
    meetingBooked: false,
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: null,
    pricingNotes: "",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "On priority eval list. Not yet contacted.",
  },

  {
    id: "prospeo",
    name: "Prospeo",
    type: "both",
    status: "evaluating",
    meetingBooked: true,
    meetingDate: "2026-04-14 10:30am PDT (done)",
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: null,
    pricingNotes: "$0.01/email lookup; 10 credits/mobile lookup",
    rateLimit: "30 req/sec",
    latencyEstimateMs: null,
    notes: "Meeting done Apr 14 with Matt Putnam + Joe Aboutariya. Granola: 304M contacts total, 125M+ phone numbers, 7-day refresh, 0.4% bounce rate, 30 req/sec. Ranked #1 enterprise email accuracy, #2 mobile by Clay/Instantly/Nooks. Pricing confirmed: $0.01/email, 10 credits/mobile. Trial setup expected end of week (Apr 18).",
    contacts: ["Matthew Putnam — matthew@prospeo.io", "Joseph Aboutariya — joseph@prospeo.io"],
    website: "prospeo.io",
  },

  {
    id: "wiza",
    name: "Wiza",
    type: "both",
    status: "evaluating",
    meetingBooked: true,
    meetingDate: "2026-04-17 9:30am PDT (done)",
    questionnaireStatus: "not-sent",
    hasApiKey: true,
    trialCredits: 7000,
    trialCreditsEquiv: "7K trial credits allocated on call",
    pricingNotes: "",
    rateLimit: "100 concurrent requests (testing)",
    latencyEstimateMs: null,
    notes: "Active email thread via Gwen. KJ Chow replied Apr 13 — Wiza #1 enterprise email accuracy, #2 mobile number accuracy (per Clay/Instantly/Nooks/Apollo rankings). Apr 16: Meeting booked with KJ Chow for Apr 17 9:30am PDT (30-min Zoom). Ross also on invite. Apr 17: Meeting done with KJ Chow + Ross. Real-time API eval. Concurrency-based limits (100 for testing), 7K credits allocated. Work email verification too slow for Chrome extension; personal emails + phone better for async workflows. Account set up on the call.",
    contacts: ["KJ Chow — kj.chow@wiza.com"],
    website: "wiza.co",
  },

  {
    id: "leadmagic",
    name: "LeadMagic",
    type: "both",
    status: "not-started",
    meetingBooked: false,
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: null,
    pricingNotes: "",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "On questionnaire eval list for both email + phone workstreams. Not yet contacted.",
  },

  {
    id: "datagma",
    name: "Datagma",
    type: "both",
    status: "evaluating",
    meetingBooked: true,
    meetingDate: "2026-03-16 11am MDT (done)",
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: null,
    pricingNotes: "$0.20/phone lookup · $10/1K email lookups",
    rateLimit: "20 calls/sec",
    latencyEstimateMs: null,
    notes: "Full discovery call done Mar 16 (Raphael Azot). Granola: real-time sourcing (no static DB — fresh each call), $0.20/phone, $10/1K emails, 20 calls/sec rate limit. Haley sent follow-up Apr 13 requesting Slack channel + trial API key.",
    contacts: ["Raphael Azot — raphael@datagma.com", "Syed — syed@datagma.com"],
    website: "datagma.com",
  },

  {
    id: "smarte",
    name: "SMARTe",
    type: "both",
    status: "evaluating",
    meetingBooked: true,
    meetingDate: "2026-03-18 10:30am PDT (done)",
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: null,
    pricingNotes: "",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "Full discovery call done Mar 18 (Vikram Maram + Sanjay Gala). Granola: 290M+ contacts, 65M companies, 75% mobile coverage in NA. API-based. Strong mobile/cell number coverage.",
    contacts: ["Vikram Maram — vikram.maram@smarte.pro", "Sanjay Gala — sanjay.gala@smarte.pro"],
    website: "smarte.co",
  },

  {
    id: "pdl",
    name: "PDL (People Data Labs)",
    type: "both",
    status: "already-evaluated",
    meetingBooked: false,
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: null,
    pricingNotes: "",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "Referenced in strategy discussions (Granola Apr meetings) as on-prem dataset option. Champify moved away from PDL. On questionnaire eval list.",
    website: "peopledatalabs.com",
  },

  {
    id: "fullenrich",
    name: "FullEnrich",
    type: "both",
    status: "already-evaluated",
    meetingBooked: false,
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: null,
    pricingNotes: "",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "Referenced in strategy discussions as key waterfall supplement vendor. On questionnaire eval list.",
    website: "fullenrich.com",
  },

  {
    id: "findymail",
    name: "Findymail",
    type: "both",
    status: "trial-active",
    meetingBooked: true,
    meetingDate: "2026-03-17 10:30am MDT (done)",
    questionnaireStatus: "not-sent",
    hasApiKey: true,
    trialCredits: 10,
    trialCreditsEquiv: "10 free email lookups",
    pricingNotes: "",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "Call done Mar 17 with Valentin Wallyn. Apr 14: Gwen looped Haley in on existing thread with Rufiz Zeynal + James Carter. Haley created shared Slack channel Apr 14 and asked for trial API key. Apr 16: Trial account created — verification + welcome email received (10 free credits, 95%+ deliverability claimed). Rufiz confirmed questions answered in Slack and provided free trial signup link. Rufiz leading this engagement; James focuses on other product. Account live at app.findymail.com. Apr 22: Rufiz back from OOO, allocated additional credits to account — ready for active testing.",
    contacts: ["Valentin Wallyn — valentin@findymail.com", "Rufiz Zeynal — rufiz@findymail.com", "James Carter — james@findymail.com"],
    website: "findymail.com",
  },

  {
    id: "aviato",
    name: "Aviato",
    type: "both",
    status: "evaluating",
    meetingBooked: true,
    meetingDate: "2026-04-14 (done)",
    questionnaireStatus: "not-sent",
    hasApiKey: true,
    trialCredits: null,
    pricingNotes: "Significant partner discount expected vs. public pricing",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "Meeting done Apr 14 with Konrad. 1.25B people, 80M companies, 400M+ personal emails. Phone numbers ~1 month out. Self-serve signup available. Positions as broad contact + company data platform. Apr 16: 2FA login email confirms account is active. Konrad replied email saying he answered all questions in the shared Slack group — shared Slack channel now set up. Granola: significant partner discount expected vs. public pricing.",
    contacts: ["Konrad — konrad@aviato.co"],
    website: "aviato.co",
  },

  {
    id: "lusha",
    name: "Lusha",
    type: "both",
    status: "evaluating",
    meetingBooked: true,
    meetingDate: "2026-04-17 9am PDT (done) + 2026-04-29 9am-9:30am PDT (booked — partnerships follow-up)",
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: null,
    pricingNotes: "",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "Apr 16: Nick Colson cancelled original 11am PDT meeting due to a home emergency and rescheduled to Apr 17 9am PDT. Apr 17: Meeting done with Nick Colson — intro partnership discussion. Nick needs manager + Israeli director approval before confirming structure. Follow-up scheduled Wed Apr 22 4pm ET. Apr 21: Haley followed up by email. Nick replied — Lusha's partnership model currently limited to API access only (no data resell). Haley clarified that Unify's use case is using Lusha API in contact enrichment waterfall surfaced to customers. Nick sent to partnerships team; expects update Thu Apr 24 morning. KEY: if Lusha considers waterfall use 'reselling', partnership may be blocked (similar to LeadIQ BYOA issue). Apr 25: Thu Apr 24 deadline for partnerships team response has passed without reply — follow up needed with Nick Colson. Apr 28: New partnerships follow-up meeting booked for Wed Apr 29, 2026 9am-9:30am PDT — Nick Colson + Miri Tamir + Orit Shilvock (both from Lusha partnerships team) accepted the invite. Lusha partnerships team is now directly engaged.",
    contacts: ["Nick Colson — nick.colson@lusha.com", "Miri Tamir — miri.tamir@lusha.com", "Orit Shilvock — orit.shilvock@lusha.com"],
    website: "lusha.com",
  },

  {
    id: "leadiq",
    name: "LeadIQ",
    type: "both",
    status: "evaluating",
    meetingBooked: true,
    meetingDate: "2026-04-15 (done) + 2026-04-17 Nabil call (done) + 2026-04-20 2pm EDT (CANCELLED)",
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: null,
    pricingNotes: "",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "Meeting done Apr 15 with Elena. Unify's need: 200K+ contacts/month not covered by current waterfall; data needed: email, phone, name, title, LinkedIn URL. Partnership model: similar to Clay's integration — requires separate legal/OEM agreement (not standard terms). Does NOT partner with Apollo (direct competitor — potential obstacle). Follow-up scheduled Apr 17 with Nabil (Head of Partnerships) to discuss commercial/OEM terms. Apr 17: Nabil call done. Key blocker confirmed: Clay integration appears to be BYOA-only, which may kill partnership viability. BYOA models are deprioritized in Unify's vendor strategy. Apr 20: Elena cancelled the follow-up meeting with Nabeel Ahmed — 'Canceling this meeting. I will send an intro email for you and Nabeel to coordinate calendars!' Awaiting Elena's intro email to connect Haley directly with Nabeel Ahmed.",
    contacts: ["Elena — elena@leadiq.com"],
    website: "leadiq.com",
  },

  {
    id: "swordfish",
    name: "Swordfish",
    type: "both",
    status: "evaluating",
    meetingBooked: true,
    meetingDate: "2026-04-22 11:30am PDT (done)",
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: null,
    pricingNotes: "Min $1K/mo (~10K contacts); custom pricing for 10K–200K contacts/month range (Drew to send). Reseller pricing ~4x standard.",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "On priority eval list. Meeting booked Apr 22 11:30am PDT with Drew Clark (VP) — drew@swordfishapp.com. Apr 22: Meeting done with Drew Clark (London-based). Swordfish specializes in personal email (#1 on Clay) and mobile phone numbers (#1 on Clay for quality). NOT a work email fill — Drew was clear this will not help work email gap. ~100M mobiles (~30M US, rest global); releasing 200–400M more mobiles in coming months. 800M people profiles, 65M company profiles (data feed option). Pricing: credits-based (mobile=15cr, email=5cr); self-serve starter/grow/pro plans in app; standard terms min 50K credits annually; reseller pricing ~4x standard. Data feed: $85K/yr (people global), $65K/yr (company). No open API spec — public docs only. Next: Haley to set up Slack channel, send questionnaire, add engineers for trial next week or week after. Drew to send pricing range for 10K–200K contacts/month.",
    contacts: ["Drew Clark (VP) — drew@swordfishapp.com"],
    website: "swordfish.ai",
  },

  {
    id: "signalhire",
    name: "SignalHire",
    type: "both",
    status: "evaluating",
    meetingBooked: true,
    meetingDate: "2026-04-16 8:30am PDT (done)",
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: null,
    pricingNotes: "Custom pricing pending for 10K–200K volume",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "Meeting done Apr 16 with Charles (charles@signalhire.net). Real-time search (no static DB), 96–97% email accuracy. Custom pricing pending for 10K–200K volume. Follow-up needed on pricing details and trial API access. Apr 22: Charles followed up asking about next steps and evaluation timeline. Apr 24: Charles sent another follow-up — needs response from Haley on where things stand.",
    contacts: ["Charles — charles@signalhire.net"],
    website: "signalhire.com",
  },

  {
    id: "signaliz",
    name: "Signaliz",
    type: "both",
    status: "not-started",
    meetingBooked: false,
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: null,
    pricingNotes: "",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "On priority eval list. Not yet contacted. Apr 15: Received 'Signaliz Major Updates 4/15/26' email from team@signaliz.com — product release announcement. Apr 26: Received 'Exciting Updates for Signaliz Users' email — new website launch + new features. Still on marketing list; not yet contacted for partnership.",
  },

  // ── Phone vendors ───────────────────────────────────────────────────────────

  {
    id: "forager",
    name: "Forager",
    type: "phone",
    status: "evaluating",
    meetingBooked: true,
    meetingDate: "2026-04-20 7pm PDT (done)",
    questionnaireStatus: "not-sent",
    hasApiKey: true,
    trialCredits: null,
    pricingNotes: "Min $1K/mo (~10K contacts); credits: mobile=15cr, email=5cr. Standard min 50K credits/yr (annual). Data feed: $85K/yr (people), $65K/yr (company). Reseller ~4x standard.",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "Meeting booked Apr 20 7pm PDT with Peter Friis (Zoom). Gwen had prior contact with Ahmed Abdelaziz. Haley looped in Apr 15. Apr 20: Meeting done with Peter Friis — #1 mobile provider on Clay (quality focus), also #1 personal email on Clay. ~100M mobiles (~30M US, rest global); releasing 200–400M more in coming months. 800M people profiles + 65M companies (data feed). Credits: mobile=15cr, email=5cr; standard min 50K credits/yr (annual contract). Data feed: $85K/yr people, $65K/yr company. Reseller pricing ~4x standard. No open API spec — public docs only. Slack channel already set up. Apr 21: Forager welcome email confirmed — account active, API key available under Account Settings. Haley to sign up self-serve; Peter will top up trial credits. Data team to test over next 2 weeks. Apr 23: Follow-up email 'Don't forget — free credits are waiting' — trial credits available but not yet claimed. Apr 25: Final check-in email 'One last thing before I go…' — offering test credits in exchange for short chat; trial credits still unclaimed.",
    contacts: ["Peter Friis — peter@forager.ai", "Ahmed Abdelaziz — ahmed@forager.ai"],
  },

  {
    id: "upcell",
    name: "upcell",
    type: "phone",
    status: "evaluating",
    meetingBooked: true,
    meetingDate: "2026-04-16 11:30am PDT (done)",
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: null,
    pricingNotes: "$100K minimum commitment",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "Meeting done Apr 16 11:30am PDT with Mark Bedard. Granola: US mobile enrichment focus, $100K minimum commitment, 60–70% match rate. High minimum is a key risk factor for commercials.",
    contacts: ["Mark Bedard — mark.bedard@upcell.io"],
  },

  {
    id: "contactout",
    name: "ContactOut",
    type: "phone",
    status: "contacted",
    meetingBooked: false,
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: null,
    pricingNotes: "",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "Meeting with Arian Pekaric was booked for Mar 12 but CANCELLED. Apr 15: Varad told Arian they're pausing vendor evaluation and will resume in coming weeks. Haley on CC. Status: on hold.",
    contacts: ["Arian Pekaric — arian@contactout.io", "Chaimaa Zirdane — chaimaa@contactout.io"],
    website: "contactout.com",
  },

  {
    id: "zeliq",
    name: "Zeliq",
    type: "phone",
    status: "evaluating",
    meetingBooked: true,
    meetingDate: "2026-04-28 7:30-8:15am PDT Group Webinar (Camille WATTEL, done) + 2026-04-28 9:30am-10am PDT 1:1 (Vincent Deloffre, done)",
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: null,
    pricingNotes: "€0.02/credit; phone=10 credits (€0.20/lookup), email=1 credit (€0.02/lookup). Min 1M credits (~$23K). POC option: 250K credits available. Credits don't expire.",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "Apr 28 group webinar demo booked with Camille WATTEL. Vincent Deloffre (vincentd@zeliq.com) reached out Apr 15 — prefers 1:1; Haley sent calendar link same day. Apr 16: Vincent accepted 1:1 meeting invite for Apr 22 9am PDT (30-min Zoom). Apr 22: Vincent declined the 9am PDT meeting — 'I've seen you've modified the time for that meeting and that will be difficult for me. I'll directly choose another slot on your calendar.' Haley replied apologizing and reshared calendar link. Apr 23: Vincent accepted new time — 1:1 meeting confirmed for Tue Apr 28, 2026 9:30am-10am PDT (Zoom). Apr 28 group webinar with Camille also still on. Apr 28: Both meetings done. Granola notes: Strong EU coverage (France, UK, US top regions — 60-65% phone, 80-85% email). More expensive than direct data providers; positioned as waterfall endpoint (similar to ZoomInfo but cheaper). Clay partnership: 4M credit packages. Partnership revenue <10% of their business. Post-meeting: Vincent emailed confirming POC batch at 250K credits, then top-up at 1M. Price €0.02/credit, phone=10 credits, email=1 credit.",
    contacts: ["Vincent Deloffre — vincentd@zeliq.com", "Camille WATTEL"],
  },

  {
    id: "surfe",
    name: "Surfe",
    type: "phone",
    status: "contacted",
    meetingBooked: false,
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: null,
    pricingNotes: "",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "Haley emailed Marta El Bay (marta.elbay@surfe.com) Apr 14 about data partnership. Marta OOO in Portugal Apr 13–16; back Apr 17. Apr 21: Haley sent follow-up. Apr 22: Marta replied — 'Apologies for the delay, I must have missed your email! Sure, happy to chat. You can see my availability here.' Marta is Head of Partnerships at Surfe. Haley to book via Marta's calendar link — next step: schedule meeting.",
    contacts: ["Marta El Bay — marta.elbay@surfe.com"],
  },

  {
    id: "betterkontact",
    name: "BetterContact",
    type: "phone",
    status: "evaluating",
    meetingBooked: true,
    meetingDate: "2026-03-16 11:30am MDT (done)",
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: null,
    pricingNotes: "$0.02/credit (enterprise tier)",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "Full discovery call done Mar 16 with Roman Hipp. Fathom meeting recap received. Granola: aggregates 20+ providers, $0.02/credit enterprise, 99–99.5% email deliverability. Uses Trestle in their phone verification waterfall.",
    contacts: ["Roman Hipp — roman@bettercontact.rocks"],
  },

  {
    id: "rocketreach",
    name: "RocketReach",
    type: "phone",
    status: "evaluating",
    meetingBooked: true,
    meetingDate: "2026-04-15 12:30pm PDT (done) + 2026-04-17 noon PDT (done) + 2026-04-21 10am PDT (done)",
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: null,
    pricingNotes: "Min $2,900/yr = 200K credits (100K emails or 33K phones); $6,000/yr = 500K credits; $10,000/yr = 1M credits. Email=2cr, phone=6cr. White label OK. Legal redlines only for contracts ≥$6K.",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "Technical call Apr 15 (Vithuson Raveenthiran). Follow-up booked Apr 17 noon with Emily Gleason + Vithuson + Ross + Varad. 750M professionals, 65M companies. Granola: exploring as 3rd/4th waterfall vendor for ~30–40% coverage gap. Apr 17: Follow-up call done with Emily Gleason + Vithuson + Ross + Varad. Trial account + test credits being set up; Haley to send data vendor questionnaire. Apr 21 10am PDT: follow-up Zoom done with Emily + Vithuson + Ross + Varad. Pricing confirmed: min $2,900/yr = 200K credits (100K emails or 33K phones); $6K/yr = 500K credits; $10K/yr = 1M credits. 1000 trial credits sent to Ross (valid through May 23). White label OK. Haley added Emily to Slack channel. Questionnaire pre-fill to be sent to Emily.",
    contacts: ["Emily Gleason — emily@rocketreach.co", "Vithuson Raveenthiran — vithuson@rocketreach.co"],
    website: "rocketreach.co",
  },

  {
    id: "pubrio",
    name: "Pubrio",
    type: "phone",
    status: "evaluating",
    meetingBooked: true,
    meetingDate: "2026-04-15 7pm PDT (done)",
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: null,
    pricingNotes: "$0.01/credit PAYG; volume discounts at 5M+ credits",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "Meeting done Apr 15 7pm PDT with Jacqueline Leung (co-founder/COO), King Lai, Plato. Originally booked Apr 13 but Haley rescheduled to Apr 15 due to conflict. Apr 16: King Lai sent enthusiastic follow-up email with requested materials attached (large ~2MB attachment). King's words: 'absolutely thrilled to be part of this journey.' Granola: $0.01/credit PAYG, volume discounts at 5M+. Granola (Apr 16): APAC-focused provider with 90% accuracy in Asia. Trial API setup planned for start of next week. Larger contract potential in 3-4 months at Unify's list-building launch.",
    contacts: ["Jacqueline Leung (co-founder/COO) — jacq.leung@pubrio.com", "King Lai — king.lai@pubrio.com", "Plato Wai — plato@pubrio.com"],
    website: "pubrio.com",
  },

  // ── Email vendors ───────────────────────────────────────────────────────────

  {
    id: "hunter",
    name: "Hunter",
    type: "email",
    status: "trial-active",
    meetingBooked: false,
    questionnaireStatus: "not-sent",
    hasApiKey: true,
    trialCredits: 50,
    trialCreditsEquiv: "50 free monthly credits",
    pricingNotes: "",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "Referenced as evaluated by Gwen in earlier vendor calls (Granola). On questionnaire eval list. Apr 15: Giovanni Lepori (giovanni@hunter.io) replied confirming he joined the shared Slack channel. Free trial account available at hunter.io. Gwen also CC'd. Apr 17: Hunter account created and validated — confirmation email + 50 free monthly credits. API onboarding email received ('Welcome to Hunter, Haley'). Account live at hunter.io.",
    contacts: ["Giovanni Lepori — giovanni@hunter.io"],
    website: "hunter.io",
  },

  {
    id: "kitt",
    name: "Kitt",
    type: "email",
    status: "contacted",
    meetingBooked: false,
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: null,
    pricingNotes: "",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "Signed up on trykitt.ai Apr 13. Got welcome email with 3-minute setup. Self-serve account. Need to test.",
    website: "trykitt.ai",
  },

  {
    id: "icypeas",
    name: "Icypeas",
    type: "email",
    status: "evaluating",
    meetingBooked: true,
    meetingDate: "2026-04-27 1pm-1:30pm PDT (done)",
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: 10000,
    trialCreditsEquiv: "~10K email lookups (Pierre to add post-meeting)",
    pricingNotes: "$500/100K searches; volume discounts available",
    rateLimit: "CTO increasing rate limits (post-meeting action)",
    latencyEstimateMs: null,
    notes: "Received newsletter from Pierre Landoin (pierre.landoin@icypeas.com) Apr 14. Apr 15: received 'What great cold emails look like' drip email. Apr 16: received 'What's a good reply rate?' drip email. Apr 13: received 'You know something I need' email — Haley replied Apr 13 introducing Unify and data partnership opportunity. Apr 20: Haley sent follow-up. Apr 21: Pierre replied agreeing to chat, shared calendar link. Apr 23: Meeting confirmed — Mon Apr 27, 2026 1pm-1:30pm PDT (Google Meet: meet.google.com/hex-xtsn-snk). Apr 24: Pierre sent data retention policy update email — changes to data storage/processing effective May 20. Apr 27: Meeting done. Granola notes: email-only enrichment (no phone), $500/100K searches (volume discounts available), 100M emails/month API capacity, 30 min downtime last year, used by Apollo/Lemlist/Instantly as first waterfall position, weaker in Spanish-speaking & Asian countries, MCP server available. Pierre's post-meeting actions: add 10K credits to account; CTO to increase rate limits. Haley's next steps: test 1K contacts via bulk search API; email Pierre questions.",
    contacts: ["Pierre-Baptiste Landoin (CEO) — pierre.landoin@icypeas.com"],
    website: "icypeas.com",
  },

  {
    id: "enrow",
    name: "Enrow",
    type: "email",
    status: "trial-active",
    meetingBooked: false,
    questionnaireStatus: "not-sent",
    hasApiKey: true,
    trialCredits: 10000,
    trialCreditsEquiv: "~10K email lookups",
    pricingNotes: "$87/mo for 10K credits ($75/mo in EUR) on monthly plan",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "Thomas from Enrow added 10,000 trial credits to account Apr 14. API key loaded and ready. Pricing: $87/mo or €75/mo for 10K credits/month. Log out and back in to see credits in UI.",
    contacts: ["Thomas — thomas@enrow.io"],
    website: "enrow.io",
  },

  {
    id: "lima-data",
    name: "Lima Data",
    type: "both",
    status: "evaluating",
    meetingBooked: true,
    meetingDate: "2026-04-14 (done)",
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: null,
    pricingNotes: "",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "Meeting done Apr 14 with Krista. 400–500M person database; work emails, phone numbers, personal emails (ranked #1–2 by Clay for personal email coverage). No waterfalling — 100% proprietary data with live SMTP verification. Real-time collection from LinkedIn, Crunchbase, Glassdoor. API-only (no UI). Prospecting API runs on Sales Nav and returns more results than traditional DBs. Next: set up Slack channel, get API docs + test credits, send questionnaire. Two-week test plan: founder week 1, engineering week 2.",
    contacts: ["Krista"],
    website: "limadata.io",
  },

  {
    id: "snovio",
    name: "Snov.io",
    type: "both",
    status: "trial-active",
    meetingBooked: true,
    meetingDate: "2026-04-14 (done)",
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: 500,
    trialCreditsEquiv: "~500 email lookups (additional credits for ~1K contact test pending)",
    pricingNotes: "Custom ultra package with credit rollover. 1 credit per valid email only.",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "Meeting done Apr 14 with Pg. Custom ultra package with credit rollover. Sub-API keys (checking with eng). Pro trial of 500 credits + Slack channel + questionnaire activating the following Monday. Primarily email enrichment. Apr 27: Active email exchange with Gabrielle — Haley requested trial of ~1K contacts for phone + email enrichment over 2-3 weeks. Gabrielle confirmed 'Sounds like a plan, Haley. No worries. Would you like to start today?' — trial starting today. Type updated to 'both' as Haley explicitly asked for phone + email enrichment.",
    contacts: ["Gabrielle (Pg) — pg@snov.io"],
    website: "snov.io",
  },

  {
    id: "dropcontact",
    name: "Dropcontact",
    type: "email",
    status: "evaluating",
    meetingBooked: false,
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: 50,
    trialCreditsEquiv: "50 email lookups",
    pricingNotes: "",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "Signed up Apr 13. Got welcome email with 50 free credits. Email-focused, European company data speciality. Denis from Dropcontact confirmed signup. Apr 16: Caroline Deparpe (integrations@dropcontact.io) replied to Haley's Unify x Dropcontact Data Partnership outreach. Key highlights: 100% real-time enrichment (no static DB), works with several platforms similar to Clay, pre-call info sent. Meeting/call to be scheduled.",
    contacts: ["Denis — dc@dropcontact.io", "Caroline Deparpe — integrations@dropcontact.io"],
    website: "dropcontact.com",
  },

  {
    id: "minerva",
    name: "Minerva",
    type: "both",
    status: "evaluating",
    meetingBooked: true,
    meetingDate: "2026-04-28 3-3:30pm PDT (done)",
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: null,
    pricingNotes: "",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "Apr 28: Intro meeting done with Jackson Engles + Daniel Saedi (transcript unavailable — follow up). Capability, pricing model, and coverage details TBD pending meeting recap from Jackson.",
    contacts: ["Jackson Engles — jackson@minerva.io", "Daniel Saedi — daniel@minerva.io"],
    website: "minerva.io",
  },

  {
    id: "contactlevel",
    name: "ContactLevel",
    type: "both",
    status: "evaluating",
    meetingBooked: true,
    meetingDate: "2026-04-15 3pm PDT (done) + 2026-04-21 2pm PDT (done)",
    questionnaireStatus: "not-sent",
    hasApiKey: false,
    trialCredits: null,
    pricingNotes: "",
    rateLimit: "",
    latencyEstimateMs: null,
    notes: "First call Apr 15 3pm PDT with Jack Caspino (jack@contactlevel.com) — 30-min demo. Apr 20: Jack booked follow-up for Apr 21 2pm PDT via cal.com. Apr 21: Follow-up call done with Jack Caspino. 780M people total, 358M with email, 199M with phone numbers. Enrichment via LinkedIn URL → phone + email. Clay partnership powers Clay's 'Audiences' feature (hashed emails + mobile ad IDs for advertising) — NOT traditional B2B enrichment waterfall. New intent data product in development (raw publisher/ad network data, ~2 weeks out). Jack to build API + send docs in a few days (traveling SE Asia Thu Apr 24). Haley to set up Slack channel, send questionnaire; data team to test week of Apr 28. Pricing flexible — Jack said 'I'm flexible here to make sure it works for both of us.'",
    contacts: ["Jack Caspino — jack@contactlevel.com"],
    website: "contactlevel.com",
  },

]
