// ─── Commercial brief data ────────────────────────────────────────────────────
// Source: Signal Vendor Commercial Brief (Notion, updated 2026-03-27)
// Keyed by vendorContact.id

export type CommitmentTier = "none" | "low" | "medium" | "high"
// none   = ✅ No commit / PAYG
// low    = 🟡 <$10K upfront
// medium = ⚠️  $10K–$50K upfront
// high   = ❌  $50K+ upfront (requires scrutiny)

export type Capability =
  | "finds-enrich"         // company finder + enrichment API
  | "enrich-only"          // bring your domain, get fields back
  | "dataset"              // bulk flat-file purchase only
  | "finds-enrich-dataset" // all three
  | "platform"             // not a traditional data vendor

export type BudgetStatus = "excluded" | "exploring" | "tentative" | "signed"
// excluded  = PAYG / not budgeting for this vendor
// exploring = evaluating — include as possible upside
// tentative = likely to sign — include in base budget
// signed    = contract executed

export type LegalStatus = "not-started" | "nda-out" | "nda-signed" | "contract-review" | "contract-signed"
// not-started     = no legal work yet
// nda-out         = NDA sent, awaiting signature
// nda-signed      = NDA executed
// contract-review = contract / MSA under legal review
// contract-signed = fully executed

// Reseller / OEM agreement review status (new legal review workstream)
export type ResellAgreementStatus =
  | "ready-to-sign"           // Agreement looks good — ready for signatures
  | "sent-redlines"           // We sent redlines / amendments; waiting on their response
  | "need-to-review"          // We have the agreement in hand; need to review it
  | "need-reseller-agreement" // Don't have an agreement yet; need to get one from them
  | "do-not-sign"             // Decided not to proceed / deprioritized

export interface VendorCommercial {
  commitmentTier: CommitmentTier | null
  commitmentLabel: string            // human-readable amount, e.g. "$150K/yr"
  pricingTldr: string                // 1–2 sentence summary
  pricingDetail?: string             // longer notes for expanded panel
  capability: Capability | null
  capabilityLabel?: string           // override display label if needed
  commercialNextStep: string
  commercialOwner: string | null
  questionnaireUrl?: string          // link to Google Doc vendor questionnaire
  contractUrl?: string               // link to latest signed/in-review contract
  annualBudgetUsd: number | null     // tentative annual spend in USD
  budgetStatus: BudgetStatus         // how firm this number is
  estimatedAnnualVolume: number | null  // rough annual enrichments/lookups at budgeted spend
  coverageNote: string               // what data this vendor provides, finance-facing
  financeNote: string                // justification / context for finance
  legalStatus: LegalStatus | null    // where are we in NDA / contract process
  resellAgreementStatus: ResellAgreementStatus | null  // reseller/OEM agreement review status
  legalNotes?: string                // notes for legal review tab
}

export const vendorCommercialData: Record<string, VendorCommercial> = {

  // ── 🟢 READY ─────────────────────────────────────────────────────────────

  harmonic: {
    commitmentTier: "medium",
    commitmentLabel: "$10K min",
    pricingTldr: "$0.04/credit, $10K upfront min. API enrichment only — no bulk, no caching.",
    pricingDetail: "$10K credit commitment required upfront, then quarterly true-up at $0.04/credit. No data caching allowed — each end-customer call must be a unique live API call. No bulk dataset available for partners.",
    capability: "finds-enrich",
    commercialNextStep: "Follow up with Mike Palmer on Apr 29 meeting outcomes — confirm contract amendment status (no-caching constraint, liability cap, indemnification redlines still outstanding). Send proposed amendments to unblock signing.",
    commercialOwner: "will",
    questionnaireUrl: "https://docs.google.com/document/d/1vjT5BINvN0k0yCoXp_NtVvPpUXgFXzcV/edit",
    contractUrl: "https://docs.google.com/document/d/1s-VVOE0sH6p2hD8wsn0vEgx6oTxwvVRgwPNi6DLC0rM/edit",
    annualBudgetUsd: 10000,
    budgetStatus: "tentative",
    estimatedAnnualVolume: 250000,
    coverageNote: "Company enrichment — firmographics, funding rounds, employee count",
    financeNote: "API-only; no data caching allowed. Strong US startup coverage.",
    legalStatus: null,
    resellAgreementStatus: "sent-redlines",
    legalNotes: "Apr 9 legal review: highest-risk contract. Issues: no data accuracy warranty, $100K liability cap, broad customer indemnification. Austin wants to proceed; Haley to send proposed amendments. Apr 16 follow-up legal review: higher liability cap remains an issue; missing non-infringement warranty flagged as additional risk. Amendments still outstanding. Apr 29: Follow-up 'Harmonic <> Unify' call done with Mike Palmer + Eric — transcript unavailable; follow up on contract amendment status and no-caching constraint.",
  },

  upriver: {
    commitmentTier: "none",
    commitmentLabel: "No commit",
    pricingTldr: "Starting $500/mo + $0.08/credit. No advance required. Pilot period available.",
    pricingDetail: "Monthly minimum $500/mo; annual contracts $800–$2K/mo. Per-credit pricing sheet available. Pilot period available for evaluation before annual commitment.",
    capability: "finds-enrich",
    commercialNextStep: "Contract signed Apr 24 — no further action needed. Loop in eng to activate integration.",
    commercialOwner: "will",
    contractUrl: "https://drive.google.com/file/d/1FkA_eCfQI4wkcMldBhyJRcOY12r4pBRc/view",
    annualBudgetUsd: null,
    budgetStatus: "excluded",
    estimatedAnnualVolume: null,
    coverageNote: "Company finder + enrichment — PAYG",
    financeNote: "PAYG — no upfront commitment; pay as we use",
    legalStatus: "contract-signed",
    resellAgreementStatus: "ready-to-sign",
    legalNotes: "Apr 7: Joe Tam sent OEM/reseller agreement. Apr 9: Legal first pass — needs indemnification + data rights statement. Apr 14: Joe accepted key edits. Apr 16: Legal review meeting completed. Apr 24: Contract signed — confirmed in Haley's group DM with Will + ADL.",
  },

  adyntel: {
    commitmentTier: "none",
    commitmentLabel: "No commit",
    pricingTldr: "500K credits = $2,604 (sub) / $3,255 (PAYG). Only charged on successful returns.",
    pricingDetail: "1 credit = 1 successful API call. 500K: $2,604 sub / $3,255 PAYG. 1M: $4,687 / $5,859. 5M: $19K / $23K. Above 5M: custom pricing, credits don't expire. ~20% cheaper on subscription vs PAYG.",
    capability: "enrich-only",
    commercialNextStep: "Contract signed Apr 24 — no further action needed. Loop in eng to activate integration.",
    commercialOwner: "adl",
    questionnaireUrl: "https://docs.google.com/document/d/1gEKLwZfPwDLH5DdSwwD3B3fYvju98y_f/edit",
    contractUrl: "https://docs.google.com/document/d/1DPZbI4ub_JPyj9Ar0ZQLczHDLju0ab4Wk9P1OC9dLWU/edit",
    annualBudgetUsd: null,
    budgetStatus: "excluded",
    estimatedAnnualVolume: null,
    coverageNote: "Contact + company enrichment — pay-per-success model",
    financeNote: "PAYG — charged only on successful returns; no upfront risk",
    legalStatus: "contract-signed",
    resellAgreementStatus: "ready-to-sign",
    legalNotes: "Apr 14: Emils shared OEM/reseller agreement Google Doc in #partner-adyntel-unifygtm. Apr 22: Adyntel responded — reviewing. Haley confirmed Adyntel purchase in team DM. Apr 24: Contract signed — confirmed in Haley's group DM with Will + ADL.",
  },

  storeleads: {
    commitmentTier: "medium",
    commitmentLabel: "$25K advance",
    pricingTldr: "$25K advance = 500K domain credits @ $0.05/credit. Usage-based after. Standard redistribution deal (same as Clay, Artisan, Genesee).",
    pricingDetail: "$25K upfront = 500K domain credits @ $0.05/credit. Usage-based pricing beyond that. Standard redistribution partner deal — same structure as Clay, Artisan, Genesee. No flexibility claimed on structure. BYOK option for customers who already have Store Leads.",
    capability: "finds-enrich",
    commercialNextStep: "Contract signed Apr 24 — no further action needed. Loop in eng to activate integration.",
    commercialOwner: "haley",
    questionnaireUrl: "https://docs.google.com/document/d/1A2C1Ox2znxGLQrwBl5Jw_PK5crh4BPjS/edit",
    contractUrl: "https://docs.google.com/document/d/1rTv7Xoq0qi0mgrHenFfj2G3TXwMRuSNlrDAEB5j5SdQ/edit",
    annualBudgetUsd: 25000,
    budgetStatus: "signed",
    estimatedAnnualVolume: 500000,
    coverageNote: "E-commerce domain data — Shopify/WooCommerce stores, traffic, tech stack",
    financeNote: "One-time $25K advance = 500K domain credits. Same deal structure as Clay and Artisan.",
    legalStatus: "contract-signed",
    resellAgreementStatus: "ready-to-sign",
    legalNotes: "Apr 7: Haley sent IP warranty + indemnification requirements to Ammar. Apr 23: Ammar sent final reseller agreement. Apr 24: Contract signed — confirmed in Haley's group DM with Will + ADL.",
  },

  theirstack: {
    commitmentTier: "none",
    commitmentLabel: "Zero upfront",
    pricingTldr: "Zero upfront. 1 credit = 1 job signal; 3 credits = 1 tech lookup. Volume discounts above 1M credits.",
    pricingDetail: "Pure PAYG — only charged when notifications fire. 1 credit = 1 job signal; 3 credits = 1 company technographic lookup. Volume discounts above 1M credits. Public pricing up to 1M; custom beyond. Best commercial model of any vendor in the eval.",
    capability: "finds-enrich",
    commercialNextStep: "Reach out to Xoel López — strongest commercial profile: zero upfront, pure PAYG. Get trial API invite + loop in finance for pricing above 1M credits.",
    commercialOwner: "adl",
    contractUrl: "https://docs.google.com/document/d/1lqJ-qMjhMAeu8B2jhkTXG4s8vXE-YiszAL6PWV1Tp0M/edit?tab=t.0",
    annualBudgetUsd: null,
    budgetStatus: "excluded",
    estimatedAnnualVolume: null,
    coverageNote: "Job posting signals + tech stack lookup — PAYG",
    financeNote: "PAYG — zero upfront, best commercial model in eval. No budget line needed.",
    legalStatus: null,
    resellAgreementStatus: "sent-redlines",
    legalNotes: "No agreement yet — PAYG model may not require formal reseller terms. Confirm with legal. Apr 21: Legal review with Alex (ADL) + Will in group DM. Key redlines being sent to TheirStack: §3.2 (end user responsibility — cannot accept; Unify doesn't control customer actions); §4.3 (direct audit of end users — not practicable for Unify customers); §6.2 (reseller indemnification not market; Unify will only indemnify for its own use/control, not end user actions); §6.3 (cannot accept indemnifying TheirStack for its own data collection practices). Unify requiring TheirStack to warrant legal data collection compliance and indemnify Unify for breach of that warrant. Alex confirmed 'let's move forward' — redlines being sent. Apr 22: Redlines confirmed sent — TheirStack trading comments; ball in their court per internal workstream update (#product-on-prem-data).",
  },

  serpstat: {
    commitmentTier: "none",
    commitmentLabel: "No commit",
    pricingTldr: "$9–10K one-time for full 1.8M domain DB dump. PAYG API also available per-credit.",
    pricingDetail: "$10K one-time for full 1.8M domain dataset (all SEO/traffic fields). PAYG per-credit API also available; partner pricing doc shared post-call. Rate limits: 1 req/sec standard, 10 req/sec top tier.",
    capability: "finds-enrich-dataset",
    commercialNextStep: "Contract signed Apr 22 — no further action needed. Loop in eng to activate integration.",
    commercialOwner: "will",
    contractUrl: "https://docs.google.com/document/d/1bcbvcU5qG81Ko4FG7v2Bt4kB-CYo8V6RXpO7tWYWoIM/edit",
    annualBudgetUsd: null,
    budgetStatus: "excluded",
    estimatedAnnualVolume: null,
    coverageNote: "SEO + web traffic data, 1.8M domain dataset",
    financeNote: "$9-10K one-time dataset option if needed; PAYG API otherwise. No recurring commitment.",
    legalStatus: "contract-signed",
    resellAgreementStatus: "ready-to-sign",
    legalNotes: "Contract v3 reviewed (Apr 9). Data rights warranty ✅, no liability cap ✅, indemnification ✅. BLOCKER: final disclaimer paragraph must be struck — negates warranty protections. Apr 14: Haley asked Eugene to repurpose crawling → API credits on $2K annual plan. Ready to sign once confirmed. Apr 16: Legal review meeting (Will + ADL) completed — Serpstat agreement markup formally reviewed and confirmed ready to sign once Eugene confirms credit repurposing. Apr 21: Will flagged Serpstat included a 2nd work order for on-prem with a signature block — Will sent request to Serpstat to remove it (already sent). Agreement should be final once on-prem work order is removed. Apr 22: Contract confirmed SIGNED per internal data vendor workstream update (#product-on-prem-data).",
  },

  openmart: {
    commitmentTier: "high",
    commitmentLabel: "$80K min",
    pricingTldr: "$80K min, $0.006/credit. Lower min = higher per-credit rate. Flexible on negotiation.",
    pricingDetail: "$80K bulk minimum. $0.006/credit at that tier. Credit costs: 1 credit = company lookup, 2 credits = email, 8 credits = phone. Lower commitment likely possible at higher per-credit rate.",
    capability: "finds-enrich",
    commercialNextStep: "Contract signed Apr 22 — no further action needed. Loop in eng to activate integration.",
    commercialOwner: "adl",
    questionnaireUrl: "https://docs.google.com/document/d/1hExzGNYBfFPnN-qB151piiGsXEIUNiTR/edit",
    contractUrl: "https://docs.google.com/document/d/1cKx4KIQXWPwCh-3DBdcDOjcjCpbcHu5-0_Mk5YizEoI/edit",
    annualBudgetUsd: 80000,
    budgetStatus: "signed",
    estimatedAnnualVolume: 13000000,
    coverageNote: "Company lookup + email + phone enrichment",
    financeNote: "~13M company lookups at $80K minimum. Negotiating minimum down; per-credit cost rises at lower volume.",
    legalStatus: "contract-signed",
    resellAgreementStatus: "need-reseller-agreement",
    legalNotes: "Mar 31: NEW deal — $15K upfront. Kathryn confirming per-credit pricing. Haley to send legal agreement template to Kathryn. Also need to set up shared Slack channel. Apr 22: Contract confirmed SIGNED per internal data vendor workstream update (#product-on-prem-data).",
  },

  // ── 🟡 WAIT ──────────────────────────────────────────────────────────────

  charmio: {
    commitmentTier: "none",
    commitmentLabel: "PAYG proposed",
    pricingTldr: "PAYG / no-commit option proposed (Option A, preferred). Final terms TBD pending Alex's response.",
    pricingDetail: "Three options proposed: Option A (PAYG/no upfront) is our preferred path. Also offered minimum commit + rev share alternatives. Awaiting Alex Nisenzon's response.",
    capability: "finds-enrich",
    commercialNextStep: "Follow up with Alex once reply received. Option A (PAYG/no upfront) is the preferred path.",
    commercialOwner: "will",
    annualBudgetUsd: null,
    budgetStatus: "excluded",
    estimatedAnnualVolume: null,
    coverageNote: "Company finder + enrichment — PAYG preferred",
    financeNote: "PAYG option being negotiated; no budget commitment expected",
    legalStatus: null,
    resellAgreementStatus: "need-reseller-agreement",
    legalNotes: "Blocked on POC scope — need to agree scope with Alex before any agreement can be drafted.",
  },

  similarweb: {
    commitmentTier: "high",
    commitmentLabel: "$50K+ / 10K credits",
    pricingTldr: "10K credits = $50K/yr ($0.417/credit). 100K credits = $130K/yr ($0.108/credit). Needs negotiation.",
    pricingDetail: "Credit-based model. Credits = # of URLs × # of metrics × time granularity. 10K credits → $50K/yr ($0.417/cr). 100K credits → $130K/yr ($0.108/cr). Need to pick specific endpoints before quoting. Trial access active.",
    capability: "finds-enrich",
    commercialNextStep: "Haley: send URL volume estimate + endpoint list to Miriam to unblock pricing quote. Will already on thread.",
    commercialOwner: "haley",
    annualBudgetUsd: 50000,
    budgetStatus: "exploring",
    estimatedAnnualVolume: 10000,
    coverageNote: "Web traffic + engagement metrics per domain — competitive intelligence",
    financeNote: "Volume TBD — final price depends on # of URLs × metrics chosen. Entry tier ~10K credit-queries.",
    legalStatus: null,
    resellAgreementStatus: "need-reseller-agreement",
    legalNotes: "Pre-commercial — CEO hasn't approved $10K 2-month POC yet. No agreement until pricing agreed.",
  },

  seranking: {
    commitmentTier: "none",
    commitmentLabel: "No commit",
    pricingTldr: "PAYG credit model. Signed Apr 28. SE Ranking issued 60M credits (10x the contracted 6M) as bonus.",
    pricingDetail: "Pure PAYG. AI search/LLM visibility data is more expensive than standard SEO data (key differentiator). Custom annual partnership pricing available. SE Ranking issued 60M credits as bonus on top of contracted 6M credits.",
    capability: "finds-enrich-dataset",
    commercialNextStep: "Contract signed Apr 28 — SE Ranking issued 60M credits (10x the contracted 6M) as bonus. No further action needed. Loop in eng to activate integration.",
    commercialOwner: "adl",
    questionnaireUrl: "https://docs.google.com/document/d/1cQ_IxMQSe7fRc3kHjAqr9tZSLCFbkwSh/edit",
    contractUrl: "https://docs.google.com/document/d/1T6wg9aSUmTEXJGBOJDnjZ4cUJR1bliDNXsyB8V_D0EM/edit",
    annualBudgetUsd: null,
    budgetStatus: "excluded",
    estimatedAnnualVolume: null,
    coverageNote: "SEO data + AI/LLM brand visibility tracking — PAYG",
    financeNote: "PAYG — no upfront. Unique differentiator: AI/LLM brand visibility data. Bonus: 60M credits issued.",
    legalStatus: "contract-signed",
    resellAgreementStatus: "ready-to-sign",
    legalNotes: "Apr 9: SE Ranking drafting custom OEM agreement with mutual indemnification. Apr 28: Contract signed — SE Ranking issued 60M credits (10x contracted 6M). Confirmed in Haley's group DM with Will + ADL.",
  },

  cbinsights: {
    commitmentTier: "high",
    commitmentLabel: "6-fig license",
    pricingTldr: "6-figure license + $0.01/Mosaic score call. Formal proposal due next week.",
    pricingDetail: "Annual license fee + per-call usage. $0.01/Mosaic score call. Separate pricing for per-call usage vs. dataset purchase. Proposal coming next week from Rawley Dawson.",
    capability: "finds-enrich-dataset",
    commercialNextStep: "Wait — formal proposal due next week from Rawley Dawson.",
    commercialOwner: "will",
    questionnaireUrl: "https://docs.google.com/document/d/1PuchAdmzhZ35EJY8sslcbeavHymK0Z_2/edit",
    annualBudgetUsd: null,
    budgetStatus: "exploring",
    estimatedAnnualVolume: null,
    coverageNote: "Mosaic scores, funding intelligence, company health signals",
    financeNote: "Awaiting formal proposal. 6-fig license is a significant line item; evaluate vs. Crunchbase for overlap.",
    legalStatus: null,
    resellAgreementStatus: "need-reseller-agreement",
    legalNotes: "Waiting for formal proposal from Rawley Dawson before any legal work can start. CEO approval required for all deals.",
  },

  dealroom: {
    commitmentTier: "medium",
    commitmentLabel: "€12K/yr",
    pricingTldr: "€12K/yr entry → €45K/yr unlimited. Best price point in the fundraising category. Apr 16: 3-month POC proposed at ~$12K/year for 50K calls.",
    pricingDetail: "Annual license, tiered by API call volume. €12K/yr entry (limited calls) → €45K/yr unlimited OEM. Apollo uses the unlimited OEM model. €12K entry is the right starting point — gives access to evaluate before scaling. Questionnaire being filled by Kjeld + Miguel as of 3/27. Apr 16 catch-up call: 3-month POC proposed at ~$12K/year for 50K calls. Engineer capacity is the current blocker to move forward.",
    capability: "finds-enrich",
    commercialNextStep: "Loop in engineer to evaluate POC — engineer capacity is the blocker identified on Apr 16 call. Then finalize 3-month POC at ~$12K/year for 50K calls.",
    commercialOwner: "will",
    questionnaireUrl: "https://docs.google.com/document/d/1XfJYV4yaO-IBs2LQwKcXcjUoxfQ2TV-L3EwgkvNXXjo/edit",
    annualBudgetUsd: 13000,
    budgetStatus: "tentative",
    estimatedAnnualVolume: null,
    coverageNote: "Fundraising data — rounds, investors, valuations, European startup coverage",
    financeNote: "Replaces Crunchbase ($150K) at ~12x lower cost for overlapping signals. Entry tier covers our expected call volume.",
    legalStatus: null,
    resellAgreementStatus: "need-reseller-agreement",
    legalNotes: "Questionnaire filling / commercial terms TBD. No reseller agreement yet — get one once commercial terms confirmed.",
  },

  theswarm: {
    commitmentTier: "none",
    commitmentLabel: "No upfront",
    pricingTldr: "Partner tier: $500/mo = 50K credits. Flat file: $10K/mo (600M profiles, AWS S3). No upfront.",
    pricingDetail: "Self-serve: $99/mo (Base), $299/mo (Premium). Partner tier: $500/mo = 50K credits (~5x cheaper at higher volumes). Flat file: $10K/mo (AWS S3; 600M profiles, 100M companies, 200M emails). Enterprise/reseller: custom — to be defined on 3/30 call. Clay uses BYOA model.",
    capability: "enrich-only",
    commercialNextStep: "Will: join 3/30 call with Grace + David — lock in enterprise/reseller partner structure.",
    commercialOwner: "will",
    questionnaireUrl: "https://docs.google.com/document/d/10pDlnPwR2NHC_QKzHUoRbVTwdofAXD-XS4O2z75CJcA/edit",
    annualBudgetUsd: null,
    budgetStatus: "excluded",
    estimatedAnnualVolume: null,
    coverageNote: "Contact enrichment, professional network graph",
    financeNote: "PAYG partner tier; no upfront. Budget line only needed if we commit to flat file.",
    legalStatus: null,
    resellAgreementStatus: "need-to-review",
    legalNotes: "Apr 2: Grace approved 90-day paid pilot ($3K/450K credits). PandaDoc Service Order Form sent — awaiting Haley's signature.",
  },

  adbeat: {
    commitmentTier: null,
    commitmentLabel: "TBD",
    pricingTldr: "TBD — Clay-style annual credit model likely. VP Ops (Mark) approval needed before terms can be offered.",
    pricingDetail: "Porter is consulting with VP Operations on partnership structure. Annual credit allocation model (similar to Clay deal) expected. Adyntel (competitor) is at $0.06/credit (50K vol), $0.05/credit (100K+) — use as anchor. Demo done 3/26.",
    capability: "enrich-only",
    commercialNextStep: "Will: wait for VP Ops approval. Reference Adyntel pricing as anchor when terms come.",
    commercialOwner: "will",
    annualBudgetUsd: null,
    budgetStatus: "exploring",
    estimatedAnnualVolume: null,
    coverageNote: "Contact enrichment — Clay-style credit model",
    financeNote: "Pricing TBD pending vendor internal approval. No budget line until terms received.",
    legalStatus: null,
    resellAgreementStatus: "need-reseller-agreement",
    legalNotes: "VP Ops approval needed before any terms can be offered. No agreement until pricing confirmed.",
  },

  beauhurst: {
    commitmentTier: "medium",
    commitmentLabel: "£20–40K/yr",
    pricingTldr: "£20–40K/yr seat-based + API. Awaiting CEO approval on their side.",
    pricingDetail: "Annual seat-based license + API integration. UK and German private company data (5M+ UK private companies from Companies House filings). Strong niche for EU coverage.",
    capability: "finds-enrich",
    commercialNextStep: "Wait — CEO approval pending on their side.",
    commercialOwner: null,
    annualBudgetUsd: 38000,
    budgetStatus: "exploring",
    estimatedAnnualVolume: null,
    coverageNote: "UK + German private company data — 5M+ companies from Companies House filings",
    financeNote: "Only vendor with deep UK private company data. Niche but high-value for EU coverage gap.",
    legalStatus: null,
    resellAgreementStatus: "need-reseller-agreement",
    legalNotes: "CEO approval needed before API/reseller pricing can be offered. Louis Scott following up.",
  },

  // ── 🔴 BLOCKED / DEPRIORITIZED ───────────────────────────────────────────

  crunchbase: {
    commitmentTier: "high",
    commitmentLabel: "$150K/yr advance",
    pricingTldr: "$150K non-refundable annual advance. Per-enrichment $0.05–$0.15/call by data type. 12-mo auto-renew.",
    pricingDetail: "Annual advance of $150K, non-refundable, invoiced at contract start. Applied as credit against enrichment fees. Per-enrichment schedule: funding/investors/financials $0.15; basic company $0.05; categories $0.07; person profile $0.07. Contract: 12 months, auto-renewing, 30-day cancellation notice. Access: API + initial data dump. Validate that $150K aligns with expected enrichment volume at blended ~$0.10–0.15/call.",
    capability: "finds-enrich",
    commercialNextStep: "Resume POC discussion with Kegan + Brett — confirm 3-month trial at $0.15/enrichment and advance structure. Chase reseller agreement + data dictionary (both overdue from Apr 9 sync). Evaluate in parallel with Dealroom (€12K) for fundraising signal coverage.",
    commercialOwner: "will",
    annualBudgetUsd: 150000,
    budgetStatus: "exploring",
    estimatedAnnualVolume: null,
    coverageNote: "Global company data — funding rounds, investors, financials",
    financeNote: "POC at $0.15/enrichment; Year 1 projection $50–100K. Advance structure TBD. Dealroom (€12K) is lower-cost alternative for overlapping signals — evaluate in parallel.",
    legalStatus: null,
    resellAgreementStatus: "need-reseller-agreement",
    legalNotes: "Apr 9 PAYG/Advance sync done with Kegan + Brett — 3-month trial at $0.15/enrichment, advance structure TBD. Crunchbase to share reseller agreement + data dictionary. Still awaiting both. Brett Collins confirmed willing to work toward terms that make sense for both sides.",
  },

  pitchbook: {
    commitmentTier: "high",
    commitmentLabel: "~$160K/yr",
    pricingTldr: "~$160K/yr min (1K users × $160/user). Deprioritized vs. Dealroom (€12–45K/yr).",
    pricingDetail: "Seat-based annual license ~$160K/yr (1K users × $160/user). Per-call API pricing TBD — Charlie Weiss sharing data eval contacts. Key question: does PitchBook's depth justify 3–13× price premium over Dealroom for overlapping signals? MCP server available for existing licensees.",
    capability: "finds-enrich",
    commercialNextStep: "Hold — wait for Charlie Weiss to share data eval contacts. High price requires careful evaluation vs. Dealroom before progressing.",
    commercialOwner: "will",
    annualBudgetUsd: 160000,
    budgetStatus: "excluded",
    estimatedAnnualVolume: null,
    coverageNote: "Venture + PE data — deep fundraising and private market intelligence",
    financeNote: "Deprioritized. Seat-based ~$160K/yr. Does not justify 3–13x premium over Dealroom for overlapping signals.",
    legalStatus: null,
    resellAgreementStatus: "do-not-sign",
    legalNotes: "Deprioritized. 3–13× premium over Dealroom for overlapping signals not justified.",
  },

  spade: {
    commitmentTier: "high",
    commitmentLabel: "6-fig OEM floor",
    pricingTldr: "6-figure OEM annual target. NDA signed 3/26. Usage estimate sent — awaiting quote from Oban.",
    pricingDetail: "Volume-based per API call / merchant enrichment. OEM/reseller model. 6-figure annual target is almost certainly too high for current volume and will need significant negotiation. NDA signed by Will 3/26. Usage estimate (~5K/mo → 20K+) sent 3/26 to unblock pricing.",
    capability: "enrich-only",
    commercialNextStep: "Will: await quote from Oban. Lily traveling through Fintech Meetup. 6-fig floor needs significant negotiation down.",
    commercialOwner: "will",
    questionnaireUrl: "https://docs.google.com/document/d/1C70UsMqyC-EiufRX2EgGEMgMDFUHN4sL/edit",
    annualBudgetUsd: null,
    budgetStatus: "exploring",
    estimatedAnnualVolume: null,
    coverageNote: "Transaction + merchant data enrichment — fintech-specific",
    financeNote: "6-fig OEM floor needs significant negotiation. Niche fintech use case. Awaiting quote.",
    legalStatus: "nda-signed",
    resellAgreementStatus: "need-reseller-agreement",
    legalNotes: "NDA signed by Will 3/26. Awaiting OEM agreement / quote from Oban. 6-fig floor needs significant negotiation down.",
  },

  "reodev": {
    commitmentTier: null,
    commitmentLabel: "Not discussed",
    pricingTldr: "No pricing discussed. Needs formal partnership proposal from us before re-engaging.",
    pricingDetail: "Call focused on integration model only. Individual API keys per customer model discussed. Company finder in development. Need formal partnership proposal outlining use case before any commercial terms can be set.",
    capability: "enrich-only",
    commercialNextStep: "Will: send formal partnership proposal before re-engaging — include high-level pricing structure and Unify's differentiation vs. Clay.",
    commercialOwner: "will",
    annualBudgetUsd: null,
    budgetStatus: "excluded",
    estimatedAnnualVolume: null,
    coverageNote: "Company enrichment — terms not yet discussed",
    financeNote: "No commercial terms yet. Needs formal proposal before re-engaging.",
    legalStatus: null,
    resellAgreementStatus: "need-reseller-agreement",
    legalNotes: "Blocked — need to send formal partnership proposal before any agreement can be discussed.",
  },

  explorium: {
    commitmentTier: "high",
    commitmentLabel: "$60K/yr min",
    pricingTldr: "$60K/yr = 6M credits ($0.0125/cr). 1cr/company, 2cr/tech, 5cr/contact. Preview before charge — only billed on used results. Only provider with intent-based list building (Bombora).",
    pricingDetail: "$60K/yr minimum = 6M credits at $0.0125/credit. Credit breakdown: 1cr/company enrichment, 2cr/technographics, 2-3cr/events, 5cr/contact enrichment. Standard 200 QPM; partners get 1,000 QPM. Preview functionality included — results shown before credits are charged. Can combine bulk data + API credits. Bulk flat file needed for on-demand filtering. Data page: companyenrich.com/our-data.",
    capability: "finds-enrich-dataset",
    commercialNextStep: "Awaiting pricing options (API-only vs bulk+API) from Roy/Omer. Haley to intro data engineer for bulk data evaluation. Target: commercial agreements signed within a few weeks.",
    commercialOwner: "haley",
    questionnaireUrl: "https://docs.google.com/document/d/1JeGvBYx-TqQKzDwjbfmLsqVczsi1lkq7/edit",
    annualBudgetUsd: 60000,
    budgetStatus: "tentative",
    estimatedAnnualVolume: 6000000,
    coverageNote: "Company enrichment + technographics + intent signals (Bombora partnership)",
    financeNote: "Only vendor with Bombora intent data. 6M credits = ~6M company enrichments or ~1.2M contact enrichments at min tier.",
    legalStatus: null,
    resellAgreementStatus: "need-reseller-agreement",
    legalNotes: "Pricing options received (API-only $50-60K/yr). Need to respond to Roy + get reseller agreement drafted.",
  },

  crustdata: {
    commitmentTier: "medium",
    commitmentLabel: "$4K/mo min",
    pricingTldr: "$4K/mo = 40K credits. Full dataset $20K/mo. Deprioritized — better for on-prem evaluation.",
    pricingDetail: "API: $4K/mo = 40K credits. Real-time: $0.10/credit (1 company/credit). Cached: $0.001/company (100 companies/credit). Full people dataset: $20K/mo ($240K/yr). Better suited for on-prem dataset evaluation vs. API enrichment vendor.",
    capability: "finds-enrich-dataset",
    commercialNextStep: "Deprioritized — better suited for on-prem dataset evaluation. No immediate action.",
    commercialOwner: null,
    annualBudgetUsd: 48000,
    budgetStatus: "exploring",
    estimatedAnnualVolume: 480000,
    coverageNote: "Company + contact enrichment, bulk dataset option",
    financeNote: "Deprioritized for API use; better suited for bulk dataset evaluation. $4K/mo = 40K enrichments/mo.",
    legalStatus: null,
    resellAgreementStatus: "need-reseller-agreement",
    legalNotes: "Deprioritized for now. No agreement needed until evaluation scope is confirmed.",
  },

  retentiondotcom: {
    commitmentTier: "none",
    commitmentLabel: "No prepaid",
    pricingTldr: "$0.05–$0.08/resolution + $1.00/domain fee. Usage-based, no prepaid. Deprioritized.",
    pricingDetail: "OEM: $0.08/resolution + $1.00/domain. Volume tiers: $0.06 at 50K, $0.05 at 100K+. Usage-based, no prepaid credits. Website visitor de-anonymization only. Skip for now.",
    capability: "enrich-only",
    commercialNextStep: "Skip for now — deprioritized.",
    commercialOwner: null,
    annualBudgetUsd: null,
    budgetStatus: "excluded",
    estimatedAnnualVolume: null,
    coverageNote: "Website visitor de-anonymization",
    financeNote: "Deprioritized. Niche use case (visitor ID only). PAYG if ever needed.",
    legalStatus: null,
    resellAgreementStatus: "do-not-sign",
    legalNotes: "Deprioritized — niche visitor de-anonymization only. Skip.",
  },

  // ── TBD / UPCOMING ────────────────────────────────────────────────────────

  hithorizons: {
    commitmentTier: "low",
    commitmentLabel: "€3.5K/60K calls",
    pricingTldr: "API: €3.5K/60K calls → €33K/6M calls. Bulk EU dataset: €220K/yr.",
    pricingDetail: "API pricing: €3,500/60K calls → €33,000/6M calls. Bulk EU dataset: €220K/yr. European company coverage specialist: 80M+ companies. 10-day trial available — activate by replying to Tibor.",
    capability: "finds-enrich",
    commercialNextStep: "Reply to Tibor Jánoška to activate 10-day API trial, then evaluate pricing tiers.",
    commercialOwner: "haley",
    questionnaireUrl: "https://docs.google.com/document/d/1_lY9njd9jy5wGnX0vAR-VDc8BGmyTHri/edit",
    annualBudgetUsd: 4000,
    budgetStatus: "exploring",
    estimatedAnnualVolume: 60000,
    coverageNote: "European company data — 80M+ companies across EU",
    financeNote: "Entry tier ~60K enrichments for €3.5K. Scales with usage. Best EU coverage option evaluated.",
    legalStatus: null,
    resellAgreementStatus: "need-reseller-agreement",
    legalNotes: "Trial not started yet. Get agreement once trial is evaluated.",
  },

  buyercaddy: {
    commitmentTier: "medium",
    commitmentLabel: "$12K–$36K",
    pricingTldr: "Signed $12K=250K credits starter plan. 1cr/firmographic, 2cr/technographic, 5cr/contact. 180K IT products tracked.",
    pricingDetail: "Signed starter plan: $12,000 = 250K credits. Growth tier available: $36,000 = 2M credits. Credit tiers: 1cr firmographic, 2cr technographic, 5cr contact/social. Can combine bulk data (S3/Snowflake monthly distribution) + API credits + contact enrichment. 180K IT products, 92K vendors, 31.2M+ companies across 55 countries. MCP server available. 50% discount from public website rates.",
    capability: "finds-enrich-dataset",
    commercialNextStep: "Contract signed Apr 28 — $12K/250K credits starter plan. No further action needed. Loop in eng to activate integration.",
    commercialOwner: "adl",
    contractUrl: "https://docs.google.com/document/d/1ZJcVg2SlfNlmn5ZDcXttVapSx_bv6ykd-E5plDNpktA/edit",
    annualBudgetUsd: 12000,
    budgetStatus: "signed",
    estimatedAnnualVolume: 250000,
    coverageNote: "Technographics — 180K IT products tracked, tech stack, IT spend, churn signals",
    financeNote: "Signed $12K starter plan = 250K enrichments/yr. Primary technographics vendor alongside HG Insights evaluation.",
    legalStatus: "contract-signed",
    resellAgreementStatus: "ready-to-sign",
    legalNotes: "Apr 8: Mitch sent DocuSign for $12K/250K credits starter plan. Apr 16: Haley flagged legal bandwidth constraints. Apr 28: Contract signed — confirmed in Haley's group DM with Will + ADL.",
  },

  builtwith: {
    commitmentTier: "none",
    commitmentLabel: "PAYG",
    pricingTldr: "PAYG Domain API credits. Volume discounts at >1M credits. No special partnership required.",
    pricingDetail: "Gary Brewer confirmed Clay just uses the standard public Domain API — no OEM/partnership deal required. Volume discounts kick in at >1M API credits.",
    capability: "enrich-only",
    commercialNextStep: "Contract signed Apr 24 — no further action needed. Loop in eng to activate integration.",
    commercialOwner: null,
    contractUrl: "https://builtwith.com/terms",
    annualBudgetUsd: null,
    budgetStatus: "excluded",
    estimatedAnnualVolume: null,
    coverageNote: "Tech stack data — public Domain API",
    financeNote: "PAYG — standard public API, no partnership needed. No budget line required.",
    legalStatus: "contract-signed",
    resellAgreementStatus: "ready-to-sign",
    legalNotes: "Apr 21: ADL flagged hollow indemnification clause in BuiltWith agreement. Apr 22: Agreement approved internally — vendor asked to revise hollow clause. Apr 24: Contract signed — confirmed in Haley's group DM with Will + ADL.",
  },

  dealfront: {
    commitmentTier: null,
    commitmentLabel: "TBD",
    pricingTldr: "Intro call Fri 3/27 9am PDT — all details TBD.",
    capability: null,
    commercialNextStep: "Attend intro call Fri 3/27 9am PDT with Matthew Fairey.",
    commercialOwner: "haley",
    annualBudgetUsd: null,
    budgetStatus: "exploring",
    estimatedAnnualVolume: null,
    coverageNote: "European B2B data — company + contact",
    financeNote: "Pricing TBD post-intro call. No budget line yet.",
    legalStatus: null,
    resellAgreementStatus: "need-reseller-agreement",
    legalNotes: "Intro call done. Pricing TBD. No agreement yet.",
  },

  hginsights: {
    commitmentTier: null,
    commitmentLabel: "TBD",
    pricingTldr: "Intro call Mar 24 — details TBD from call notes. Apr 15 meeting done with Ted West (Ted@springdb.io); Katrina OOO. NDA being sent. Follow-up Apr 21 noon-12:45pm PDT with Katrina Cho + David Crossman.",
    capability: "enrich-only",
    commercialNextStep: "Scope data validation exercise with Ted + David Crossman. HG expects 2-year ramped agreement (Clay model). POC first, then ramp to multi-year min commit. Key: call firmographic + technographic together for 88–90% fill rate vs 60% with separate providers. Fix NDA effective date (2025 → 2026). Get formal pricing from Katrina. Competing with BuyerCaddy for tech stack coverage.",
    commercialOwner: "haley",
    annualBudgetUsd: null,
    budgetStatus: "exploring",
    estimatedAnnualVolume: null,
    coverageNote: "Technographics — tech intelligence, IT spend data",
    financeNote: "Pricing TBD. Competing with BuyerCaddy for tech stack coverage — only one likely to be signed.",
    legalStatus: "nda-out",
    resellAgreementStatus: "need-reseller-agreement",
    legalNotes: "Apr 15: Meeting with Ted West (ted@springdb.io) — Katrina Cho was OOO. Ted provided Unify context to HG Insights. NDA being sent (confirmed by Ted on Apr 15 call). Apr 21: Will flagged NDA effective date shows 2025 — Haley to ask HG Insights to update to correct 2026 date. Apr 21: Solution Deep Dive call done with Katrina Cho + David Crossman. NDA may not be fully executed (Ted mentioned 'I don't know if the NDA has gone over' on the call). HG Insights expects 2-year ramped agreement (Clay model; Clay now nearly 7-figure ARR). POC + ramp structure needed. Data fabric in scope: technographics + firmographics + corporate hierarchy + TrustRadius intent. No reseller agreement until NDA signed and pricing confirmed. Apr 21: Haley confirmed NDA is ready to sign and asked Ted to send DocuSign to connor@unifygtm.com. Ted replied: Katrina sending NDA to Connor via DocuSign before EOD Apr 21. NDA DocuSign in Connor's inbox — pending Connor's signature. Also need to flag 2025→2026 effective date correction once signed.",
  },

  // ── CONTACT VENDOR COMMERCIAL NOTES ────────────────────────────────────────

  datagma: {
    commitmentTier: null,
    commitmentLabel: "TBD",
    pricingTldr: "$0.20/phone lookup · $10/1K email lookups. Real-time sourcing — no static DB. 20 calls/sec rate limit.",
    pricingDetail: "Real-time sourcing — data is fetched fresh per call (no static database). $0.20 per phone lookup, $10 per 1,000 email lookups. 20 calls/sec rate limit. No bulk dataset option.",
    capability: "enrich-only",
    commercialNextStep: "Await Raphael's Slack response on trial credits (Haley replied May 1 confirming API directly is preferred; account signed up). Once credits loaded, test coverage and latency before any commercial discussion.",
    commercialOwner: "haley",
    annualBudgetUsd: null,
    budgetStatus: "exploring",
    estimatedAnnualVolume: null,
    coverageNote: "Email + phone contact enrichment — real-time sourcing, no static database. Full discovery call done Mar 16.",
    financeNote: "PAYG — no upfront. $0.20/phone, $10/1K emails. Trial API key setup in progress as of Apr 29.",
    legalStatus: "not-started",
    resellAgreementStatus: null,
    legalNotes: "Apr 29: Raphael created Slack channel and is setting up trial API key. May 1: Haley confirmed API directly preferred and signed up — awaiting Raphael's Slack response with trial credits. No legal docs exchanged yet. No legal work until trial evaluation complete.",
  },

  upcell: {
    commitmentTier: "high",
    commitmentLabel: "$100K/yr min",
    pricingTldr: "$100K annual minimum commitment. US mobile enrichment focus, 60–70% match rate. Haley to check with finance on feasibility.",
    pricingDetail: "US mobile enrichment specialist. $100K minimum annual commitment. 60–70% match rate. High minimum is the key risk factor — needs finance sign-off before proceeding further.",
    capability: "enrich-only",
    commercialNextStep: "Check with finance on $100K minimum feasibility before progressing. High minimum relative to expected mobile enrichment volume.",
    commercialOwner: "haley",
    annualBudgetUsd: 100000,
    budgetStatus: "exploring",
    estimatedAnnualVolume: null,
    coverageNote: "US mobile phone enrichment — 60–70% match rate",
    financeNote: "$100K minimum is above typical contact vendor spend. Needs explicit finance approval before committing.",
    legalStatus: "not-started",
    resellAgreementStatus: "need-reseller-agreement",
    legalNotes: "Apr 16: Meeting done with Mark Bedard (mark.bedard@upcell.io). $100K minimum commitment flagged. No legal work started — pending finance feasibility check.",
  },

  leadiq: {
    commitmentTier: null,
    commitmentLabel: "TBD",
    pricingTldr: "OEM/partnership structure TBD. Key blocker: Clay integration appears BYOA-only, which may kill partnership viability. BYOA models are deprioritized at Unify.",
    pricingDetail: "Partnership model similar to Clay's integration — requires separate legal/OEM agreement (not standard terms). Does NOT partner with Apollo (direct competitor). Apr 17: Nabil (Head of Partnerships) call confirmed Clay integration is BYOA-only — major blocker. Apr 20 follow-up with Elena + Nabeel Ahmed to clarify.",
    capability: "enrich-only",
    commercialNextStep: "Await Elena's intro email to connect Haley directly with Nabeel Ahmed (Apr 20 follow-up was cancelled). Confirm whether non-BYOA OEM path is available. If BYOA-only, deprioritize.",
    commercialOwner: "haley",
    annualBudgetUsd: null,
    budgetStatus: "exploring",
    estimatedAnnualVolume: null,
    coverageNote: "Email + phone contact enrichment — 750M professionals",
    financeNote: "No commercial terms yet. BYOA blocker may make this vendor non-viable for Unify's model.",
    legalStatus: "not-started",
    resellAgreementStatus: "need-reseller-agreement",
    legalNotes: "Apr 15: Meeting with Elena — separate OEM agreement required (not standard terms). Apr 17: Nabil (Head of Partnerships) call done — BYOA concern surfaced. Apr 20: Elena cancelled the follow-up meeting with Nabeel Ahmed — said she will send an intro email for Haley to coordinate directly with Nabeel. No legal work until partnership model confirmed viable.",
  },

  rocketreach: {
    commitmentTier: "none",
    commitmentLabel: "Min $2,900/yr",
    pricingTldr: "Min $2,900/yr = 200K credits (100K emails or 33K phones). $6K/yr = 500K credits; $10K/yr = 1M credits. Email=2cr, phone=6cr.",
    pricingDetail: "Annual commitment, credits provisioned upfront. 200K credits = $2,900/yr; 500K = $6,000/yr (biannual payments); 1M = $10,000/yr (quarterly payments). Email costs 2 credits (~$0.029/email at base tier), phone costs 6 credits (~$0.087/phone). White label OK — no attribution required. DPA standard. Legal redlines/questionnaires only for contracts ≥$6K.",
    capability: "enrich-only",
    commercialNextStep: "Send questionnaire pre-fill to Emily Gleason. Send Unify's standard DPA. After trial evaluation (1000 credits to Ross, valid May 23), target $6K/yr (500K credits) if coverage is strong.",
    commercialOwner: "haley",
    annualBudgetUsd: 6000,
    budgetStatus: "exploring",
    estimatedAnnualVolume: 500000,
    coverageNote: "Phone + email enrichment — 750M professionals, 65M companies. Real-time email validation included. Targeting ~30–40% coverage gap fill.",
    financeNote: "Min $2,900/yr entry tier; $6K/yr likely right for supplemental waterfall coverage. No upfront beyond annual commit. White label OK.",
    legalStatus: "not-started",
    resellAgreementStatus: "need-reseller-agreement",
    legalNotes: "Apr 21: Pricing call done with Emily Gleason. White label confirmed OK. DPA: Haley flagged Unify has its own DPA for personal data vendors; Emily said 'should be fine.' Legal redlines only for contracts ≥$6K. No agreement drafted yet — pending trial evaluation.",
  },

  lusha: {
    commitmentTier: null,
    commitmentLabel: "TBD",
    pricingTldr: "Partnership model TBD — Lusha currently limits partners to API access only (no data resell). Awaiting partnerships team response by Thu Apr 24 on whether waterfall API use is permitted.",
    pricingDetail: "Apr 17: Intro call with Nick Colson. Partnership structure needs manager + Israeli director approval. Apr 21: Nick clarified Lusha's current model is API access only — no data resell to end users. Key question: does using Lusha API in Unify's waterfall (enrichment for customers) count as 'reselling'? Nick escalated to partnerships team; response expected Thu Apr 24.",
    capability: "enrich-only",
    commercialNextStep: "Apr 29 partnerships meeting done (Nick Colson + Miri Tamir + Orit Shilvock). Transcript unavailable — follow up with Nick to confirm whether waterfall API use is permitted. If blocked (like LeadIQ BYOA), deprioritize. If permitted, get pricing and structure.",
    commercialOwner: "haley",
    annualBudgetUsd: null,
    budgetStatus: "exploring",
    estimatedAnnualVolume: null,
    coverageNote: "Contact enrichment — email + phone. Large B2B database. Partnership model unclear.",
    financeNote: "No commercial terms yet. Partnership viability gated on Thu Apr 24 response from Lusha partnerships team.",
    legalStatus: "not-started",
    resellAgreementStatus: "need-reseller-agreement",
    legalNotes: "Apr 21: Haley clarified Unify's use case (waterfall API, not traditional resell). Nick sent to partnerships team. No legal work until partnership model confirmed viable. Apr 25: Thu Apr 24 deadline for partnerships team response has passed without reply — follow up with Nick Colson needed. Apr 28: New follow-up meeting booked for Apr 29 9am PDT — Nick Colson + Miri Tamir + Orit Shilvock (Lusha partnerships) accepted invite. Partnerships team now directly engaged. Apr 29: Meeting done (9:15-9:45am PDT) with Nick Colson + Miri Tamir + Orit Shilvock. Transcript unavailable — follow up to confirm outcome on waterfall API use permissions.",
  },

  swordfish: {
    commitmentTier: "low",
    commitmentLabel: "Min $1K/mo",
    pricingTldr: "Min $1K/mo (~10K contacts). Custom pricing for 10K–200K contacts/month range TBD from Drew. Reseller pricing ~4x standard.",
    pricingDetail: "Credit-based model. Mobile phone = 15 credits, email = 5 credits. Minimum $1,000/month for ~10,000 contacts. Custom pricing for higher volumes (Drew Clark to send range for 10K–200K contacts/month). Reseller/OEM pricing is ~4x the standard pricing. Data feed: $85K/yr (800M people globally), $65K/yr (65M companies). Self-serve starter/grow/pro plans also available in app.",
    capability: "enrich-only",
    commercialNextStep: "Eval complete (May 1). Trial active — 1K credits from Carla (Apr 30, valid ~May 30). Review eval results (32.8% personal email, 41% phone hit rate) and share with Drew. Get Drew's pricing range for 10K–200K contacts/month; evaluate reseller (~4x) vs. standard model before any commitment.",
    commercialOwner: "haley",
    annualBudgetUsd: null,
    budgetStatus: "exploring",
    estimatedAnnualVolume: null,
    coverageNote: "Personal email (#1 on Clay for quality) + mobile phone numbers (#1 on Clay for quality). NOT work email focused. ~100M mobiles; 200-400M more releasing soon.",
    financeNote: "Pricing TBD from Drew. Min ~$12K/yr at base tier. Reseller model ~4x standard. Strongest for personal email + mobile coverage gap; NOT for work email.",
    legalStatus: "not-started",
    resellAgreementStatus: "need-reseller-agreement",
    legalNotes: "Apr 22: Intro call done with Drew Clark (VP, London-based). No legal work started — pending trial evaluation and pricing confirmation from Drew.",
  },

  trigify: {
    commitmentTier: "none",
    commitmentLabel: "PAYG (no minimum)",
    pricingTldr: "PAYG: $0.012/credit, no minimum. Annual commitment tiers also available.",
    capability: "enrich-only",
    commercialNextStep: "Await Trigify's response to our comments on their OEM/reseller agreement.",
    commercialOwner: "haley",
    annualBudgetUsd: null,
    budgetStatus: "exploring",
    estimatedAnnualVolume: null,
    coverageNote: "Social signal intelligence — LinkedIn, X, Reddit, YouTube, podcasts, TikTok, GitHub, HackerNews engagement data",
    financeNote: "PAYG with no minimum — low commitment risk. Social Topics endpoint used by Clay. Credits at $0.012 each.",
    legalStatus: "not-started",
    resellAgreementStatus: "sent-redlines",
    legalNotes: "Apr 22: Comments sent on Trigify OEM/reseller agreement per internal workstream update (#product-on-prem-data) — trading redlines.",
  },

  semrush: {
    commitmentTier: "high",
    commitmentLabel: "6-fig/yr min",
    pricingTldr: "6-fig annual minimum. Volume-based pricing grid across traffic, backlinks, and AI visibility APIs. Bundling multiple APIs gets better rates. Adobe acquisition adds exec approval overhead.",
    pricingDetail: "Six-figure annual minimum — similar structure to Clay partnership model. Cost drivers: API access fees + usage volume. Economies of scale when bundling multiple APIs. Recommended phase 1: (1) traffic & engagement data (domain-level), (2) backlinks DB (2nd largest after Google, Authority Score 0–100), (3) AI/LLM visibility (share of voice, brand mentions in LLMs). Approval process: Haley discusses 6-fig min with finance → demo to Semrush → exec summary required by Semrush leadership (Adobe acquisition) → final proposal with pricing breakdown.",
    capability: "enrich-only",
    commercialNextStep: "Haley: discuss 6-fig annual minimum with finance team. Then: schedule demo/workflow presentation to Semrush team → submit exec summary (required for Adobe acquisition) → receive final partnership proposal.",
    commercialOwner: "haley",
    annualBudgetUsd: null,
    budgetStatus: "exploring",
    estimatedAnnualVolume: null,
    coverageNote: "Web traffic, backlinks, AI/LLM brand visibility per domain",
    financeNote: "6-fig minimum TBD; exact amount depends on API bundle selected. Evaluating vs. SE Ranking (PAYG) for cost efficiency.",
    legalStatus: null,
    resellAgreementStatus: "need-reseller-agreement",
    legalNotes: "Pre-commercial. Need finance sign-off on 6-fig minimum, then exec summary, then proposal. No agreement until that process is complete.",
  },

  wattdata: {
    commitmentTier: "none",
    commitmentLabel: "TBD",
    pricingTldr: "No pricing known yet. In trial/evaluation — Slack channel #unify-watt-data active. Contacts: Jared Parker (jared@wattdata.ai), John (john@wattdata.ai).",
    pricingDetail: "Pre-commercial. Trial access in progress as of Apr 27 2026. Watt Data offers agent-native data infrastructure (15T relationships). No pricing proposals received yet.",
    capability: "finds-enrich",
    commercialNextStep: "Follow up on Apr 27 meeting with Jared Parker (transcript unavailable). Capture use case, coverage scope, and pricing structure. Kunal to continue testing.",
    commercialOwner: "haley",
    annualBudgetUsd: null,
    budgetStatus: "exploring",
    estimatedAnnualVolume: null,
    coverageNote: "Agent-native data infrastructure — people, company, intent signals",
    financeNote: "No budget allocated. Pre-commercial trial only.",
    legalStatus: "not-started",
    resellAgreementStatus: null,
    legalNotes: "Apr 27: Trial started. Meeting with Jared Parker done Apr 27 (calendar confirmed Jared accepted; John needsAction). Transcript unavailable — follow up. No legal docs exchanged yet.",
  },

  minerva: {
    commitmentTier: "none",
    commitmentLabel: "TBD",
    pricingTldr: "No pricing known yet. Intro meeting booked Apr 28 9–9:30am PDT. Contacts: Jackson Engles (jackson@minerva.io), Daniel Saedi (daniel@minerva.io).",
    pricingDetail: "Pre-commercial. Intro/demo call scheduled Apr 28 2026. Category and pricing model TBD post-meeting.",
    capability: "enrich-only",
    commercialNextStep: "May 1: Account created at minerva.io (welcome email received). Log in and explore platform. Follow up with Jackson Engles for API access details, trial credits, use case fit, and pricing model.",
    commercialOwner: "haley",
    annualBudgetUsd: null,
    budgetStatus: "exploring",
    estimatedAnnualVolume: null,
    coverageNote: "TBD — pending Apr 28 intro call",
    financeNote: "No budget allocated. Pre-commercial.",
    legalStatus: "not-started",
    resellAgreementStatus: null,
    legalNotes: "Apr 27: Added as new vendor. Apr 28: Intro meeting done with Jackson Engles (jackson@minerva.io) + Daniel Saedi (daniel@minerva.io). Transcript unavailable — follow up for capability, pricing model, and coverage notes. No legal docs yet.",
  },

  icypeas: {
    commitmentTier: "none",
    commitmentLabel: "No commit / PAYG",
    pricingTldr: "$500/100K email searches; volume discounts available. Email-only enrichment (no phone). Used by Apollo, Lemlist, Instantly as first waterfall position.",
    pricingDetail: "$500 per 100K searches. Volume discounts available at higher tiers. Charged only for email enrichment — no phone data. 100M emails/month API capacity. Weaker in Spanish-speaking & Asian countries. MCP server available for Claude integration.",
    capability: "enrich-only",
    commercialNextStep: "Test 1K contacts via bulk search API using 10K trial credits (Pierre adding post-meeting). CTO increasing rate limits. Email Pierre questions as they arise. Evaluate coverage vs. existing waterfall providers.",
    commercialOwner: "haley",
    annualBudgetUsd: null,
    budgetStatus: "exploring",
    estimatedAnnualVolume: null,
    coverageNote: "Email enrichment only — no phone. Used by Apollo/Lemlist/Instantly. Weaker in Spanish-speaking & Asian countries.",
    financeNote: "PAYG at $500/100K searches. No upfront commitment. Budget line only needed if trial coverage is strong enough to warrant waterfall inclusion.",
    legalStatus: "not-started",
    resellAgreementStatus: "need-reseller-agreement",
    legalNotes: "Apr 27: Meeting done with Pierre-Baptiste Landoin (CEO). 10K trial credits being added. No legal docs exchanged yet. Pierre noted data retention policy changes effective May 20 — review before any agreement.",
  },

  zeliq: {
    commitmentTier: "medium",
    commitmentLabel: "~$23K min (1M credits)",
    pricingTldr: "€0.02/credit. Phone=10cr (€0.20/lookup), email=1cr (€0.02/lookup). Min 1M credits (~$23K). POC: 250K credits. Credits don't expire.",
    pricingDetail: "Pre-pay credit model. 1M credits = ~$23K. Phone numbers cost 10 credits per lookup (€0.20); emails cost 1 credit (€0.02). POC batch of 250K credits available for testing, then top-up at 1M. Credits never expire. Positioned as waterfall endpoint similar to ZoomInfo but cheaper. Not a direct data provider — aggregates from sources.",
    capability: "enrich-only",
    commercialNextStep: "Pricing confirmed in writing by Vincent via email Apr 28 (€0.02/cr, phone=10cr, email=1cr; POC 250K credits then top-up at 1M). Accept POC offer and start 250K credit test batch. Evaluate EU phone/email coverage vs. other waterfall vendors.",
    commercialOwner: "haley",
    annualBudgetUsd: 23000,
    budgetStatus: "exploring",
    estimatedAnnualVolume: null,
    coverageNote: "Phone + email enrichment. Strong EU/Oceania/NA coverage (France, UK, US top regions). 60–65% phone, 80–85% email in top regions. Comparable to ZoomInfo; better European coverage than US-based providers.",
    financeNote: "Pre-pay model. Min ~$23K for 1M credits. POC at 250K credits first. Partnership revenue <10% of their business — not their core product.",
    legalStatus: "not-started",
    resellAgreementStatus: "need-reseller-agreement",
    legalNotes: "Apr 28: Intro meeting done with Vincent Deloffre (Head of Revenue). No legal docs exchanged yet. Clay partnership uses 4M credit packages — similar structure expected.",
  },

  snovio: {
    commitmentTier: "none",
    commitmentLabel: "Custom Ultra package",
    pricingTldr: "Custom Ultra package from 200K credits. 1 credit per valid email only (no charge for invalid). Trial of ~1K contacts starting Apr 27.",
    pricingDetail: "Credit-based model. Custom Ultra package available at 200K+ credits with rollover. Only charged on valid email returns. Sub-API key per customer ID (feasibility being checked with engineering). Primarily email enrichment; also has phone coverage.",
    capability: "enrich-only",
    commercialNextStep: "Confirm trial credits loaded (Gabrielle to set up today Apr 27). Test ~1K contacts for phone + email enrichment over 2-3 weeks. Send vendor questionnaire. Set up shared Slack channel.",
    commercialOwner: "haley",
    annualBudgetUsd: null,
    budgetStatus: "exploring",
    estimatedAnnualVolume: null,
    coverageNote: "Email + phone enrichment. Targeting ~30% coverage not covered by existing two providers.",
    financeNote: "PAYG credit model with rollover. No upfront beyond commit tier. Budget line TBD pending trial evaluation.",
    legalStatus: "not-started",
    resellAgreementStatus: "need-reseller-agreement",
    legalNotes: "Apr 14: First meeting with Gabrielle (Pg). Apr 27: Email exchange — trial starting today. No legal docs exchanged yet.",
  },

}
