export type EmailStatus = "needs-response" | "waiting-on-them" | "none"
export type ActionOwner = "me" | "will" | "them"
export type VendorTier = "P0" | "P1" | "P2" | null
export type VendorStatus =
  | "active"          // intro done, in progress
  | "trial"           // active trial / meeting done
  | "meeting-booked"  // meeting scheduled
  | "blocked"         // hard blocker (rate limit, NDA, etc.)
  | "do-not-contact"  // explicitly flagged
  | "pending"         // no contact yet
// Commercial status from Signal Vendor Commercial Brief (Will's doc)
export type CommercialStatus =
  | "ready"           // 🟢 pricing clear, start commercial conversation now
  | "wait"            // 🟡 follow-up / proposal already in motion
  | "blocked"         // 🔴 blocked on us (need to send proposal/estimate) or deprioritized
  | null              // not yet assessed

export interface ActionItem {
  id: string
  text: string
  owner: ActionOwner
  done: boolean
}

export interface VendorContact {
  id: string
  name: string
  tier: VendorTier
  category: string         // free text, can be multi-value
  lastContactDate: string | null
  emailStatus: EmailStatus
  emailSubject?: string
  signal: string           // high-level overview (1–3 sentences)
  hasApiKey: boolean
  latencyTestRun: boolean
  actionItems: ActionItem[]
  notes: string[]          // searchable context blobs
  overallStatus: VendorStatus
  commercialStatus: CommercialStatus
  contacts: string[]        // ["Name — email", "Name — email"]
  slackChannel?: string
  attentionLink?: string
  granolaLink?: string
  pricing?: string
}

export const vendorContacts: VendorContact[] = [
  // ── P0 ────────────────────────────────────────────────────────────────────

  {
    id: "charmio",
    name: "Charm.io",
    tier: "P0",
    category: "Ecommerce · Social Listening",
    lastContactDate: "2026-04-01",
    emailStatus: "none",
    signal:
      "Brand discovery & analysis. Apr 1 demo cancelled — Haley declined (aligning internally), Alex replied 'No problem.' Partnership proposal needed before rescheduling. Dataset size, geo coverage, pricing all TBD.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "charm-1", text: "Attend rescheduled demo Wed Apr 1 1:30–2pm PDT with Alex Nisenzon", owner: "me", done: true },
      { id: "charm-2", text: "Write up partnership proposal (required before rescheduling demo — they need clearer proposal first)", owner: "me", done: false },
      { id: "charm-3", text: "Reschedule demo with Alex once proposal is ready", owner: "me", done: false },
      { id: "charm-4", text: "Reach out to Charm.io with partnership proposal", owner: "will", done: false },
    ],
    notes: [
      "Category: Ecommerce, Social Listening",
      "Signal / Data Type: Brand discovery & analysis",
      "Apr 1 demo cancelled — Haley declined (aligning internally); Alex Nisenzon replied 'No problem'",
      "Demo rescheduled from Mar 25 → Apr 1 → now cancelled; needs re-booking after proposal",
      "All data fields TBD — post-demo",
    ],
    overallStatus: "active",
    commercialStatus: "blocked",
    contacts: ["Alex Nisenzon (lead)","Mia Leonhardt — mia@charm.io"],
  },

  {
    id: "crunchbase",
    name: "Crunchbase",
    tier: "P0",
    category: "Fundraising & Company Intelligence",
    lastContactDate: "2026-04-01",
    emailStatus: "needs-response",
    emailSubject: "Kegan asking what advance range works for Unify — respond in #crunchbase-unify",
    signal:
      "Best-in-class funding/M&A signals. Kegan sent one-pager + enrichment schedule Mar 23. Haley asked about company finder/query capability Mar 25 — Kegan confirmed list-build and enrichment are the same event (all returned fields count as enrichment). Mar 30: Haley pushed back on $150K minimum, asked about pay-as-you-go or flexible minimum. Mar 31 + Apr 1: Kegan following up — says commit is just an advance against expected usage, asking what range works for Unify. Needs response.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "cb-1", text: "Reply to Kegan in #crunchbase-unify with advance range preference — Haley already said $150K is a nonstarter, Kegan says it's just an advance against usage (not a hard minimum); propose a starting range", owner: "me", done: false },
      { id: "cb-2", text: "Clarify company finder/query capability vs enrichment-only model", owner: "them", done: false },
    ],
    notes: [
      "Category: Fundraising & Company Intelligence",
      "Met Mar 12 with Brett Collins; Kegan joined #crunchbase-unify Mar 23",
      "Strong API. Unique investor relationship data. Industry standard for funding/firmographic data.",
      "Kegan sent one-pager on data partnerships + full enrichment schedule with per-action pricing (Mar 23)",
      "Haley asked Mar 25: per-enrichment fee only? Does it support company finder/query capability?",
      "Slack: #crunchbase-unify",
      "Auth: API key via sales",
      "Daily refresh",
      "Granola: https://notes.granola.ai/d/fe7f1c94-e0cb-4ac8-8de8-e2ec31af915b",
    ],
    overallStatus: "active",
    commercialStatus: "wait",
    contacts: ["Brett Collins — bcollins@crunchbase.com","Kegan — kegan@crunchbase.com"],
    slackChannel: "#crunchbase-unify",
    granolaLink: "https://notes.granola.ai/d/fe7f1c94-e0cb-4ac8-8de8-e2ec31af915b",
  },

  {
    id: "reodev",
    name: "reo.dev",
    tier: "P0",
    category: "Developer Intent",
    lastContactDate: "2026-03-31",
    emailStatus: "needs-response",
    emailSubject: "Achintya replied — confirmed they have all data formats needed; reply with next steps",
    signal:
      "Only dev-motion vendor. Developer intent signals from GitHub activity, hiring, tech orgs, first-party JS. 68–72% GitHub company match rate. Global, real-time. Individual API key per customer (Ocean.io model). Pricing TBD — internet says $500–$3K/mo. Mar 31: Achintya reviewed partnership doc and confirmed reo.dev has all the data and formats Unify needs — positive signal. Needs reply.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "reo-1", text: "Reply to Achintya's Mar 31 email — he confirmed they have all data formats needed, advance to next steps", owner: "me", done: false },
      { id: "reo-2", text: "Reach out to achintya@reo.dev with formal partnership proposal", owner: "will", done: false },
      { id: "reo-3", text: "Add CTO to technical discussion; clarify Unify delivery model (API vs flat file)", owner: "me", done: false },
    ],
    notes: [
      "Met Mar 17 with Achintya Gupta",
      "Dev-focused only. Open to 3rd-party data partnership.",
      "Only dev-motion vendor in the market",
      "68-72% GitHub company match rate; 2-3% for Reddit/Stack Overflow",
      "Auth: Individual API key per customer (Ocean.io model)",
      "Batch: max 1,000 rows per batch call",
      "Only integrations: Apollo, Outreach, Marketo, HubSpot — no Clay model yet",
      "Pricing: internet says $500–$3K/mo; needs partnership proposal first",
      "They are vetting Unify — need to send partnership proposal",
      "Granola: https://notes.granola.ai/d/e2092165-5b7f-426a-a8ca-db0907da14fa",
    ],
    overallStatus: "active",
    commercialStatus: "blocked",
    contacts: ["Achintya Gupta — achintya@reo.dev"],
    granolaLink: "https://notes.granola.ai/d/e2092165-5b7f-426a-a8ca-db0907da14fa",
  },

  {
    id: "harmonic",
    name: "Harmonic.ai",
    tier: "P0",
    category: "Fundraising & Company Intelligence",
    lastContactDate: "2026-04-03",
    emailStatus: "waiting-on-them",
    emailSubject: "Mike agreed to start next week — coordinate trial API key kickoff",
    signal:
      "Existing Unify customer. 33M+ companies globally, very strong on private companies and startups. Early detection via legal filings. Real-time signals: funding, departmental headcount, founder tracking. $0.04/API call, $10K upfront commit. No data caching — each end-customer needs a unique call. Apr 3: Mike Palmer (back from conference) confirmed 'lets do it!' and is ready to start next week. Dropped OpenAPI spec: https://api.harmonic.ai/openapi.json. Trial API key kickoff pending.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "harm-1", text: "Mike Palmer to finalize fields Harmonic is comfortable exposing via API", owner: "them", done: false },
      { id: "harm-2", text: "Review partnership structure posted by Mike in #harmonic-unify and confirm if terms work", owner: "me", done: false },
      { id: "harm-3", text: "Coordinate trial API key kickoff with Mike for week of Apr 7 (he confirmed ready Apr 3)", owner: "them", done: false },
      { id: "harm-4", text: "Review OpenAPI spec dropped by Mike: https://api.harmonic.ai/openapi.json", owner: "me", done: false },
    ],
    notes: [
      "Slack channel: #harmonic-unify",
      "Category: Fundraising & Company Intelligence",
      "33M+ companies globally (37M total dataset); strong on private companies & startups",
      "Early detection specialist via legal filings + hard-to-access sources",
      "Picks up funding events before public announcements",
      "Departmental headcount breakdown available",
      "85% of customers = VC firms (strong startup/SMB validation)",
      "Existing Unify customer",
      "Auth: API key (auth required for full docs)",
      "Pricing: $0.04/API call; $10K upfront commit (quarterly true-up)",
      "NO bulk/Snowflake dump for partners; NO data caching allowed",
      "Each end-customer needs unique API call — no re-serving cached data",
      "1,000 free trial credits (pending from Mike Palmer)",
      "API: REST or GraphQL; enrichment endpoint only; 5-8 key fields per company",
      "Granola: https://notes.granola.ai/d/cf73611b-10dc-425e-b036-5f64d2330c62",
    ],
    overallStatus: "active",
    commercialStatus: "ready",
    contacts: ["Mike Palmer — mike@harmonic.ai"],
    slackChannel: "#harmonic-unify",
    granolaLink: "https://notes.granola.ai/d/cf73611b-10dc-425e-b036-5f64d2330c62",
    pricing: "$0.04/call; $10K upfront commit (quarterly true-up); NO caching",
  },

  {
    id: "openmart",
    name: "OpenMart",
    tier: "P0",
    category: "Company Data",
    lastContactDate: "2026-03-31",
    emailStatus: "waiting-on-them",
    emailSubject: "Kathryn to confirm per-credit pricing + overage terms; Haley to send legal template",
    signal:
      "Only SMB vendor on Clay. 10M+ SMB companies + contacts. US, CA, EU, AU, NZ. AI-powered owner name lookup via gov filings — no LinkedIn dependency. Mar 31 meeting with Kathryn Wu + Will: NEW DEAL — $15K upfront commit (vs standard $80K) with higher per-credit rate. Overage pricing to match Clay. Top 3 endpoints: search business, find decision makers, detect tech stack. Kathryn confirming per-credit pricing + overage terms. Haley to send legal agreement template.",
    hasApiKey: true,
    latencyTestRun: true,
    actionItems: [
      { id: "om-1", text: "Attend follow-up meeting with Kathryn Wu — Tue Mar 31 11am PT", owner: "me", done: true },
      { id: "om-2", text: "Set up shared Slack (invite kathryn@openmart.com + Richard)", owner: "me", done: false },
      { id: "om-3-orig", text: "Kathryn to confirm per-credit pricing + overage terms with co-founder", owner: "them", done: false },
      { id: "om-6", text: "Send legal agreement template to Kathryn (1-2 days)", owner: "me", done: false },
      { id: "om-4", text: "Retest Enrich Company endpoint with restored credits (12 successes only — low confidence)", owner: "me", done: false },
      { id: "om-5", text: "Confirm cold start latency for Search (credits exhausted before cold sweep)", owner: "me", done: false },
    ],
    notes: [
      "Category: Company Data — SMB focus",
      "10M+ businesses, US/CA/EU/AU/NZ coverage",
      "Monthly refresh",
      "Auth: Bearer token (Authorization: Bearer YOUR_API_KEY)",
      "Search warm avg 133ms, p50 129ms, p95 153ms — competitive. Cold start unknown.",
      "Enrich Company warm avg 386ms, p50 398ms, p95 553ms — directional only (12 successes)",
      "Credits exhausted during latency test run (Run 1 returned 402 errors)",
      "Trial plan caps Search at limit:1 per query — hard blocker for production",
      "Batch: async; tasks: find_people, lookup_people, lookup_business_email, find_tech; poll GET /api/v1/task/batch/{id}/status",
      "GDPR + CCPA compliant",
      "Mar 31 meeting: NEW pricing offer — $15K upfront (vs standard $80K); higher per-credit rate; overage to match Clay",
      "Top 3 endpoints to focus on: search business, find decision makers, detect tech stack",
      "25% MoM growth after Clay integration — partnership validation",
      "Pricing: $15K upfront commit (lower entry point); per-credit pricing TBD (higher than $0.006 standard)",
      "Rate limit: HTTP 429 on exceed; custom by plan",
      "Attention: https://app.attention.tech/conversations/6f649ae1-f40a-4203-abdb-b1e29556a9d4",
      "Granola (Mar 31): https://notes.granola.ai/d/8708541b-1938-4eb4-a366-39a3908b4b76",
    ],
    overallStatus: "active",
    commercialStatus: "ready",
    contacts: ["Kathryn Wu — kathryn@openmart.com","Willy E — willy.e@openmart.com"],
    attentionLink: "https://app.attention.tech/conversations/6f649ae1-f40a-4203-abdb-b1e29556a9d4",
    granolaLink: "https://notes.granola.ai/d/8708541b-1938-4eb4-a366-39a3908b4b76",
    pricing: "$15K upfront commit (vs $80K std); per-credit pricing TBD at higher rate",
  },

  // ── P1 ────────────────────────────────────────────────────────────────────

  {
    id: "theorg",
    name: "The Org",
    tier: "P1",
    category: "Network & Relationship Signals",
    lastContactDate: "2026-03-20",
    emailStatus: "none",
    signal:
      "World's largest org chart network: 1M org charts, 50M contacts (US + Western Europe). AI predicts manager relationships. Sources: public team pages, LinkedIn data, news/social, self-verification. Signal tracking (promotions, new hires) available in product but not yet licensed externally. ~$100K/yr estimate.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "org-1", text: "Review API docs; follow up with Christian re: org chart licensing + flat file options", owner: "me", done: false },
      { id: "org-2", text: "Send thoughtful partnership proposal to Christian — he's cautious about licensing; we'd be a different use case than Clay", owner: "me", done: false },
      { id: "org-3", text: "Reach out to christian@theorg.com with proposal once ready", owner: "will", done: false },
    ],
    notes: [
      "Met Mar 20 with Christian Wylonis + Varad",
      "Category: Network & Relationship Signals — org chart data",
      "1M org charts, 50M contacts (US + Western Europe)",
      "AI predicts manager relationships from public sources",
      "Sources: public team pages, LinkedIn data, news/social, company self-verification",
      "API: 1 credit = manager lookup; 10 credits = full org chart JSON",
      "Signal tracking (promotions, new hires) in product but NOT yet licensed externally",
      "Bespoke AI signals available (custom pipelines per customer)",
      "Same APIs used by Clay & Apollo; closed deal with RocketReach recently",
      "Real-time waterfall validation; anonymized flat file available",
      "Pricing: similar to BCG deal (~$100K/yr); requires flat file + legal framework",
      "Christian open to partnership — Unify won't compete in org chart space",
      "Auth: API key",
      "Granola: https://notes.granola.ai/d/bf415981-4235-4a62-8f24-14c9c0ca05c4",
    ],
    overallStatus: "active",
    commercialStatus: "blocked",
    contacts: ["Christian Wylonis — christian@theorg.com"],
    granolaLink: "https://notes.granola.ai/d/bf415981-4235-4a62-8f24-14c9c0ca05c4",
    pricing: "~$100K/yr est. (similar to BCG deal); credit-based",
  },

  {
    id: "beauhurst",
    name: "Beauhurst",
    tier: "P1",
    category: "Company Data",
    lastContactDate: "2026-03-20",
    emailStatus: "waiting-on-them",
    emailSubject: "Louis Scott to follow up re: reseller/API partnership model",
    signal:
      "UK/German private company data. 5M+ UK companies; Germany launched 2025 (EU expansion 2–3 yrs). Daily refresh. £20–40K/yr seat-based. API/reseller pricing TBD — needs CEO approval. Web APIs + native HubSpot & Salesforce integrations.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "bh-1", text: "Await email follow-up from Louis Scott re: reseller/API partnership model (this/next week)", owner: "them", done: false },
    ],
    notes: [
      "Category: Company Data — UK + Germany private companies",
      "5M+ UK companies; Germany launched 2025 (EU expansion in 2-3 yrs)",
      "Daily refresh",
      "Pricing: £20-40K/yr seat-based; API/reseller needs CEO approval before offering",
      "Web APIs + native HubSpot & Salesforce integrations",
      "Louis Scott is the contact; needs to go back to CEO first on API/reseller pricing",
      "Auth: not publicly documented",
      "Granola: https://notes.granola.ai/d/061e5aa1-3899-406c-a718-1ac197404bf6",
    ],
    overallStatus: "active",
    commercialStatus: "wait",
    contacts: ["Louis Scott — louis.scott@beauhurst.com"],
    granolaLink: "https://notes.granola.ai/d/061e5aa1-3899-406c-a718-1ac197404bf6",
    pricing: "£20-40K/yr seat-based; API/reseller pending CEO approval",
  },

  {
    id: "apify",
    name: "Apify",
    tier: "P1",
    category: "Web Scraper · Ecommerce · Social Listening · Geo/Location",
    lastContactDate: "2026-03-20",
    emailStatus: "waiting-on-them",
    emailSubject: "Dmitry to send 5-10 Apify-owned actor recs + Slack channel invite",
    signal:
      "Web scraping infra — 3,000+ actor marketplace covering any site, social media, job boards. Global, real-time. Pay-per-compute-unit. LinkedIn scrapers are community-only (no SLA). MCP integration available. Apify-owned actors: Google Maps scraper + Ecommerce tool.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "api-1", text: "Receive 5-10 Apify-owned actor recs + Slack channel invite from Dmitry", owner: "them", done: false },
      { id: "api-2", text: "Loop in eng + finance for volume estimates (needed for pricing negotiation)", owner: "me", done: false },
      { id: "api-3", text: "Schedule separate commercial call", owner: "me", done: false },
    ],
    notes: [
      "Category: Ecommerce, Social Listening, Geographic / Location Data, Web Scraper",
      "3,000+ actor marketplace; any site, social media, job boards",
      "Global coverage; real-time",
      "Pay-per-compute-unit; actors free or paid in marketplace",
      "Sample price: $0.004 per LinkedIn profile (community actor)",
      "Can only negotiate discounted pricing with Apify-OWNED actors, not community",
      "REST API + actor SDK; webhooks; cloud or self-hosted",
      "Auth: Bearer token (Authorization header) or ?token= URL param",
      "Rate limits: 250K req/min global; 60 req/sec default; 200 req/sec KV store; 400 req/sec actor ops",
      "HTTP 429 + exponential backoff on rate limit",
      "Bulk: async polling + S3 export; sync timeout=300s max",
      "MCP integration available",
      "LinkedIn scrapers are community-only — no SLA",
      "White-label vs standard API key model discussed",
      "Attention: https://app.attention.tech/conversations/94c6610d-22b9-48f1-9897-d561d7df1a08",
      "Granola: https://notes.granola.ai/d/b6bc4a00-ee4a-465e-950b-2728e52db81a",
    ],
    overallStatus: "active",
    commercialStatus: "wait",
    contacts: ["Garrett Grindstaff — garrett.grindstaff@apify.com","Dmitry Chepurnikh — dmitry@apify.com"],
    attentionLink: "https://app.attention.tech/conversations/94c6610d-22b9-48f1-9897-d561d7df1a08",
    granolaLink: "https://notes.granola.ai/d/b6bc4a00-ee4a-465e-950b-2728e52db81a",
    pricing: "Pay-per-compute-unit; varies by actor; $0.004/LinkedIn profile (sample)",
  },

  {
    id: "adyntel",
    name: "Adyntel",
    tier: "P1",
    category: "Advertising Intelligence",
    lastContactDate: "2026-04-03",
    emailStatus: "waiting-on-them",
    emailSubject: "Haley sent Calendly Apr 3 to schedule PAYG pricing call — await booking from Andrei/Emils",
    signal:
      "Ad spend signals: Google, Meta, LinkedIn. ~2.5M domains, 8-month history, continuous refresh. 10K credits added to account. Will introduced Mar 24. Emils confirming database product endpoints coming week of Mar 30. LinkedIn Ads and Google Ads usable synchronously (~1.3–1.4s cold). Facebook Ads cold start up to 10s — async only. Apr 3: Haley reached out to schedule PAYG pricing call — ready to purchase a credit package.",
    hasApiKey: true,
    latencyTestRun: true,
    actionItems: [
      { id: "ad-5", text: "Await Andrei/Emils booking on Calendly for PAYG pricing call (Haley sent link Apr 3)", owner: "them", done: false },
      { id: "ad-1", text: "Test with the 10K credits Andrei added — run latency + quality checks", owner: "me", done: false },
      { id: "ad-2", text: "Clarify Facebook Ads cold start SLA — is 7–10s first-request latency by design or fixable?", owner: "me", done: false },
      { id: "ad-3", text: "Evaluate database product endpoints from Emils (coming week of Mar 30)", owner: "me", done: false },
      { id: "ad-4", text: "Investigate 28% data fill on Facebook Ads (actual gap vs field-name mismatch?)", owner: "me", done: false },
    ],
    notes: [
      "Category: Advertising Intelligence — ad spend signals",
      "~2.5M domains; 8-month historical ad spend trend",
      "Auth: single API key (api_key + email in request body)",
      "Facebook Ads: warm avg 2,371ms, cold avg 2,000–10,000ms, data fill 28%. Async only.",
      "LinkedIn Ads: warm avg 1,329ms, cold avg 1,307ms, data fill 94%. Usable synchronously.",
      "Google Ads: warm avg 1,393ms, cold avg 1,424ms, data fill 83%. Usable synchronously.",
      "Domain Keywords: warm avg 806ms, cold avg 874ms, data fill 0% (field-name mismatch suspected).",
      "Burst: FB/LI/Google Ads parallelize well; Domain Keywords queues (wall=2,432ms vs avg=1,451ms)",
      "Credits never expire; pricing TBD at 100K+ credit volumes",
      "2nd product: list building filtered by ad behavior",
      "Rate limit: no 429 in 40 requests (FB Ads test)",
      "Attention: https://app.attention.tech/conversations/ea3aeb7f-b82f-486a-9c09-375e13fef0c6",
      "Granola: https://notes.granola.ai/d/a21cae5d-8a9e-4381-b4ba-ff5359d56acf",
    ],
    overallStatus: "active",
    commercialStatus: "ready",
    contacts: ["Andrei Baloleanu — andrei@adyntel.com","Emils Vēveris — emils@adyntel.com"],
    slackChannel: "#partner-adyntel-unifygtm",
    attentionLink: "https://app.attention.tech/conversations/ea3aeb7f-b82f-486a-9c09-375e13fef0c6",
    granolaLink: "https://notes.granola.ai/d/a21cae5d-8a9e-4381-b4ba-ff5359d56acf",
    pricing: "Custom at 100K+ credits; credits never expire; pricing estimate pending",
  },

  {
    id: "rb2b",
    name: "RB2B",
    tier: "P1",
    category: "Website Visitor",
    lastContactDate: "2026-04-03",
    emailStatus: "none",
    signal:
      "Person-level website de-anonymization. US: 40–45% person-level, 70–80% total. Global: 30–35% company only. Real-time webhook. OEM-ready multi-tenant model. $0.08/resolution. GDPR consent-gated; cookie notice required. Apr 2: Kaley (Retention.com) set up OEM account. Apr 3: Robb sent 'Welcome to the RB2B OEM Program — Next Steps' email. OEM account is live — add billing details to complete setup.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "rb2b-1", text: "Sign up at app.rb2b.com → notify Robb/Kaley to flip account to OEM mode", owner: "me", done: true },
      { id: "rb2b-3", text: "Notify Robb/Kaley to flip newly created RB2B account to OEM mode (signed up Apr 2)", owner: "me", done: true },
      { id: "rb2b-4", text: "Add billing details to RB2B OEM account and complete setup steps from Robb's welcome email (Apr 3)", owner: "me", done: false },
      { id: "rb2b-2", text: "Estimate customer web traffic volume for pricing model", owner: "me", done: false },
    ],
    notes: [
      "Category: Website Visitor de-anonymization (person + company)",
      "US: 40-45% person-level match; 70-80% total de-anon",
      "Global: 30-35% company-level only (person-level is US-focused)",
      "Real-time webhook delivery (NOT a REST API — JS snippet + webhook)",
      "OEM-ready multi-tenant model",
      "Pricing: $0.08/resolution; $0.06 at 50K+; $0.05 at 100K+",
      "GDPR: consent-gated; requires cookie notice + privacy policy",
      "No rate limits — event-driven architecture",
      "No batch — event stream only",
      "Sign up at app.rb2b.com → flip to OEM",
      "Attention: https://app.attention.tech/conversations/cfe81b97-1485-4313-8b20-aeff1377f625",
      "Granola: https://notes.granola.ai/d/86fb0180-8ed7-4f66-90e2-eb305f4e1a35",
    ],
    overallStatus: "trial",
    commercialStatus: "ready",
    contacts: ["Robb Clarke — robb@rb2b.com", "Kaley Vilmont — kaley@retention.com"],
    attentionLink: "https://app.attention.tech/conversations/cfe81b97-1485-4313-8b20-aeff1377f625",
    granolaLink: "https://notes.granola.ai/d/86fb0180-8ed7-4f66-90e2-eb305f4e1a35",
    pricing: "$0.08/resolution; $0.06 at 50K+; $0.05 at 100K+",
  },

  {
    id: "theswarm",
    name: "TheSwarm",
    tier: "P1",
    category: "Network & Relationship Signals",
    lastContactDate: "2026-04-02",
    emailStatus: "none",
    signal:
      "Relationship mapping via former colleague + education overlap network (NOT LinkedIn 2nd-degree). 600M profiles (300M clean), 100M companies. $12K/yr = 1.8M credits. Apr 2: Grace approved 90-day paid pilot — $3K for 450K credits (quarter of yearly). Unused credits roll over to annual plan. PandaDoc Service Order Form sent by Grace Apr 2 — awaiting Haley's signature.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "ts-1", text: "Await Grace's response on 90-day paid pilot request (or annual commit if pilot not possible)", owner: "them", done: true },
      { id: "ts-5", text: "Review and sign PandaDoc Service Order Form for $3K 90-day pilot (450K credits) — sent by Grace Apr 2", owner: "me", done: false },
      { id: "ts-2", text: "Test via Swarm MCP: create team in UI, plug API key into Claude Desktop, run sample queries (partner permissions now active)", owner: "me", done: false },
      { id: "ts-3", text: "Send sample queries to Olivier (e.g. find fintech companies I'm most connected to in SF)", owner: "me", done: false },
      { id: "ts-4", text: "Forward pricing structure to Will for commercial review once pilot/annual terms confirmed", owner: "me", done: false },
    ],
    notes: [
      "Mar 30 call with Grace (SF) + Olivier (north of SF)",
      "Category: Network & Relationship Signals",
      "Relationship mapping based on former colleagues + education overlaps — NOT LinkedIn 2nd-degree connections",
      "600M profiles (300M clean/quality-filtered), 100M companies",
      "Network mapper endpoint (partner key): maps org network on first call (few minutes), then instant on subsequent calls",
      "Search endpoint: natural language or structured query → returns IDs (free) → fetch profiles (costs credits)",
      "Can combine: 'find fintech companies in SF where I have connections' = one search query",
      "LinkedIn URL available on 100% of profiles; emails available but not optimized for outreach — for matching only",
      "1 credit = 1 successful fetch (person OR company profile OR warm intro path)",
      "Enterprise minimum: $12K/yr = 1.8M total credits (~150K/mo); yearly pool (not monthly expiration)",
      "Overages: 10% premium over per-credit cost; alerts at 80% usage",
      "Self-serve premium plans on website are different from partner enterprise tier",
      "Testing: create Swarm account, create team(s), get API key per team, use MCP on Claude Desktop",
      "Haley signed up for self-serve account; account ready ~Mar 31",
      "White-label possible; users can optionally connect LinkedIn (Chrome extension) to add their own connections",
      "Granola: https://notes.granola.ai/d/f66cee5e-38b1-4c34-8faa-f1dc3ec1a668",
    ],
    overallStatus: "active",
    commercialStatus: "ready",
    contacts: ["David Connors — david@theswarm.com","Grace — grace@theswarm.com","Olivier — olivier@theswarm.com"],
    slackChannel: "#theswarm-unify",
    granolaLink: "https://notes.granola.ai/d/f66cee5e-38b1-4c34-8faa-f1dc3ec1a668",
    pricing: "$12K/yr = 1.8M credits total (~150K/mo). 1 credit = 1 successful fetch. Overages at 10% premium.",
  },

  {
    id: "similarweb",
    name: "SimilarWeb",
    tier: "P1",
    category: "Tech Stack & Technographics · Website Intelligence",
    lastContactDate: "2026-04-06",
    emailStatus: "none",
    signal:
      "Website traffic & digital intelligence: visits, growth signals, marketing mix, technographics. Trial active as of Mar 23. Fastest vendor in latency eval (~100–170ms REST cold). MCP-native. Apr 2: Haley asked about monthly self-serve plan (CEO can't commit to $50K). Apr 3: Miriam confirmed $50K is standard starting price but offered a $10K 2-month POC. Apr 6: Miriam followed up again — checking if CEO is open to the POC. Still needs a response.",
    hasApiKey: true,
    latencyTestRun: true,
    actionItems: [
      { id: "sw-1", text: "Miriam to send tiered pricing (volume-based) — Will requested on Mar 24", owner: "them", done: true },
      { id: "sw-4", text: "Reply to Miriam in #unify-similarweb — confirm if CEO is open to $10K 2-month POC (she offered Apr 3)", owner: "me", done: false },
      { id: "sw-2", text: "Log in to trial account at similarweb.com and test API endpoints", owner: "me", done: false },
      { id: "sw-3", text: "Run latency tests from AWS us-east-1 (current numbers are from laptop)", owner: "me", done: false },
    ],
    notes: [
      "Met Mar 16 with Aaron Wong, Miriam, Mcadory (data licensing)",
      "Category: Tech Stack & Technographics; Website Intelligence",
      "13M+ US domains; 10B+ globally. Tier 1: NA, UK, AU, CA strong; limited in China.",
      "Daily refresh (72hr lag); monthly typical",
      "Latency eval: REST avg 78–193ms warm; 100–170ms cold. No cache bias by company size.",
      "Batch API: 72–97s end-to-end — async only, not for real-time",
      "Use cases: ecommerce growth signals, company qualification by traffic, lead discovery",
      "Auth: API key header",
      "Rate limit: 10 req/s; no 429 in production-paced tests",
      "MCP servers available",
      "Pricing: credit-based (domains × data points × granularity); hesitant to give estimate",
      "Trial key: global/world-level data only — no country-level breakdown",
      "S3/flat file pending discussion",
      "Granola: https://notes.granola.ai/d/dd5cfbe8-4d09-43d5-892e-88d045a4db91",
    ],
    overallStatus: "active",
    commercialStatus: "blocked",
    contacts: ["Miriam Troen-Krasnow — miriam.troenkrasnow@similarweb.com","Aaron Wong — aaron.wong@similarweb.com"],
    slackChannel: "#unify-similarweb",
    granolaLink: "https://notes.granola.ai/d/dd5cfbe8-4d09-43d5-892e-88d045a4db91",
    pricing: "Credit-based (domains × data points × granularity); tiered pricing pending",
  },

  {
    id: "champify",
    name: "Champify",
    tier: "P1",
    category: "Champion Tracking",
    lastContactDate: "2026-03-12",
    emailStatus: "waiting-on-them",
    emailSubject: "Stephen to send bullet list of API functions",
    signal:
      "End-to-end champion tracking: clean CRM → match LinkedIn → track job change → enrich → sync. 24x close rate vs other outbound signals. Checks every ~10 days. Also building new hire finder. Clay pays ~$30K/yr for matching API only. Global, daily rolling check.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "champ-1", text: "Receive bullet list of API functions from Stephen Ruff", owner: "them", done: false },
      { id: "champ-2", text: "Run test data on champion tracking endpoint", owner: "me", done: false },
      { id: "champ-3", text: "Get intro to Rory at Five by Five (flat-rate contact DB referral)", owner: "me", done: false },
    ],
    notes: [
      "Met Mar 12 with Stephen Ruff & Colby Adams",
      "Category: Champion Tracking — job change signals",
      "Clay uses only matching API ($30K/yr). Full product: clean → match → track → enrich → CRM sync.",
      "Handles messy CRM inputs (not just clean data)",
      "Checks every ~10 days rolling",
      "Also building new hire finder feature",
      "Referred Five by Five as flat-rate contact DB",
      "24x close rate vs other outbound signals (company claim)",
      "Auth: TBD",
      "Rate limits: TBD — function list pending from Stephen",
      "Daily (rolling ~10 day check)",
      "Pricing: Clay pays ~$30K/yr for matching API only; full product custom",
      "Granola: https://notes.granola.ai/d/7aa667d9-2609-4c2a-83eb-444bb130ce88",
    ],
    overallStatus: "active",
    commercialStatus: null,
    contacts: ["Stephen Ruff","Colby Adams"],
    granolaLink: "https://notes.granola.ai/d/7aa667d9-2609-4c2a-83eb-444bb130ce88",
    pricing: "Clay pays ~$30K/yr for matching API; full product custom",
  },

  {
    id: "explorium",
    name: "Explorium",
    tier: "P1",
    category: "Company Data · Intent · Enrichment",
    lastContactDate: "2026-03-31",
    emailStatus: "needs-response",
    emailSubject: "Roy sent pricing options (API-only $50-60K; bulk+API TBD) — needs response",
    signal:
      "Only provider with intent-based list building (3-yr Bombora partnership). 18 event types: funding, hiring, product launches, etc. Natural language queries via MCP. Preview before charge. Mar 31 meeting done with Roy, Omer, Jane Farris. Roy sent pricing post-call: API-only starting at $50-60K/yr; combined bulk+API also available. Partnership min $50K. Intro data engineer for bulk eval still needed.",
    hasApiKey: true,
    latencyTestRun: false,
    actionItems: [
      { id: "exp-1", text: "Attend Explorium meeting Tue Mar 31 9–9:30am PT (rescheduled from Mar 25)", owner: "me", done: true },
      { id: "exp-2", text: "Add eng team member to Mar 31 Explorium demo", owner: "me", done: true },
      { id: "exp-4", text: "Receive pricing options (API-only vs bulk+API) from Roy/Omer", owner: "them", done: true },
      { id: "exp-6", text: "Reply to Roy's pricing email — discuss API-only vs bulk+API structure", owner: "me", done: false },
      { id: "exp-3", text: "Use 100 trial credits + 1K bonus credits for POC file enrichment test", owner: "me", done: false },
      { id: "exp-5", text: "Intro data engineer to Explorium team for bulk data evaluation", owner: "me", done: false },
    ],
    notes: [
      "Met Mar 18 with Omer Har (CEO/Co-founder, Tel Aviv) + Roy Yarkoni (NC)",
      "Mar 31 call with Roy, Omer, Jane Farris — pricing options received",
      "Category: Company Data, Intent (Bombora partnership), Enrichment, Technographics, Events",
      "30+ data endpoints; 2K-3K new users/day on By Prospecting brand",
      "Global coverage",
      "Only provider with intent-based list building via 3-year Bombora partnership",
      "18 event types: funding, hiring, product launches, etc.",
      "Natural language queries via MCP (preview results before credits charged!)",
      "POC options: file enrichment test or API trial credits",
      "Auth: API key",
      "Rate limits: 200 QPM standard; 1,000 QPM for partners",
      "Throttle / HTTP 429 on rate limit",
      "Pagination: up to 100 records/page",
      "100 trial credits active as of Mar 22",
      "Pricing: API-only starting at $50-60K/yr; bulk+API combined also available; $50K min partnership commit",
      "Credit model: 1cr/company, 5cr/contact enrichment, 2cr/tech, 2-3cr/events",
      "Following Clay partnership model: bulk company data flat files + select API endpoints",
      "Attention: https://app.attention.tech/conversations/f3dbf724-017e-4d22-bb93-1b5574dd598d",
      "Granola (Mar 31): https://notes.granola.ai/d/c442f9b1-389f-40d3-adb0-90af7b0f6178",
    ],
    overallStatus: "active",
    commercialStatus: "ready",
    contacts: ["Omer Har — omer@explorium.ai","Roy Yarkoni — roy.yarkoni@explorium.ai"],
    attentionLink: "https://app.attention.tech/conversations/f3dbf724-017e-4d22-bb93-1b5574dd598d",
    granolaLink: "https://notes.granola.ai/d/c442f9b1-389f-40d3-adb0-90af7b0f6178",
    pricing: "API-only: $50-60K/yr; bulk+API also available; $50K min partnership commit",
  },

  {
    id: "storeleads",
    name: "Store Leads",
    tier: "P1",
    category: "Company Data · Ecommerce · Tech Stack",
    lastContactDate: "2026-03-26",
    emailStatus: "none",
    signal:
      "Only ecommerce-specific directory. 14M+ global ecommerce sites (Shopify, WooCommerce, etc.). ~100% Shopify coverage, virtually all ecommerce globally. Weekly refresh. $25K advance = 500K domain credits @ $0.05/credit. Standard redistribution deal (same as Clay, Artisan, Genesee). GDPR + CCPA. Mar 26: Will signed the 1-month internal use / dev access agreement.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "sl-1", text: "Receive 1-month dev access agreement from Ammar (cofounder) to sign", owner: "them", done: true },
      { id: "sl-2", text: "Loop in eng team — dev access agreement signed by Will on Mar 26", owner: "me", done: false },
    ],
    notes: [
      "Met Mar 16 with Ammar (cofounder)",
      "Category: Company Data, Ecommerce, Tech Stack & Technographics",
      "14M ecommerce websites globally; ~100% Shopify coverage",
      "50+ filters: platform, tech stack, sales estimate, traffic, category",
      "Weekly refresh",
      "Pricing: $25K advance = 500K domain credits @ $0.05/credit; usage-based after 500K",
      "Standard redistribution deal — same as Clay, Artisan, Genesee (no flexibility claimed)",
      "BYOK option: customers who already have Store Leads can bring their own key",
      "REST API: domain enrichment + list query endpoints; 10-domain free preview",
      "GDPR + CCPA compliant",
      "Auth: TBD (not publicly documented)",
      "1-month dev access agreement pending from Ammar before full contract",
      "Granola: https://notes.granola.ai/d/3a068c60-7c4c-4c65-9d08-4ad32180608f",
    ],
    overallStatus: "active",
    commercialStatus: "ready",
    contacts: ["Ammar — ammar@storeleads.app"],
    slackChannel: "#storeleads-unify",
    granolaLink: "https://notes.granola.ai/d/3a068c60-7c4c-4c65-9d08-4ad32180608f",
    pricing: "$25K advance = 500K domain credits ($0.05/cr); usage-based after",
  },

  {
    id: "cbinsights",
    name: "CB Insights",
    tier: "P1",
    category: "Fundraising & Company Intelligence",
    lastContactDate: "2026-03-31",
    emailStatus: "none",
    signal:
      "Predictive intelligence: proprietary Mosaic score (12-month growth/funding/acquisition probability, built with US gov data). 10–11M companies, VC-backed & high-growth focus. 6-figure license fee + $0.01/data point. CEO approval required for all deals. Meeting confirmed: Mon Apr 6 10–10:30am PT with Nathan Lowery + Ken Nie (both accepted invite).",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "cbi-1", text: "Reply to Nathan Lowery — propose Apr 6 or 7 between 12–3pm ET", owner: "me", done: true },
      { id: "cbi-5", text: "Attend CB Insights call Mon Apr 6 10–10:30am PT with Nathan Lowery + Ken Nie", owner: "me", done: false },
      { id: "cbi-2", text: "Await trial portal access from Ken Nie", owner: "them", done: false },
      { id: "cbi-3", text: "Review data dictionary (predictive vs company profile fields)", owner: "me", done: false },
      { id: "cbi-4", text: "Request standard packaging + pricing proposal — note: CEO approval required for all partnerships", owner: "me", done: false },
    ],
    notes: [
      "Category: Fundraising & Company Intelligence, Company Data",
      "10-11M companies; VC-backed & high-growth focus",
      "Proprietary Mosaic score: 12-month growth/funding/acquisition probability (built with US gov data)",
      "Holistic company analysis: management team, market maturity, product traction",
      "Global coverage",
      "Predictive intelligence (vs historical data — key differentiator)",
      "CEO approval required for ALL partnership deals",
      "Pricing: 6-figure license fee + $0.01/data point (each datapoint type varies — needs breakdown)",
      "Nathan Lowery replied Mar 29 — OOO this week; wants to connect Mon Apr 6 or Tue Apr 7 12–3pm ET; will review eval questions in meantime",
      "Meeting confirmed: Nathan Lowery + Ken Nie both accepted invite for Mon Apr 6 10–10:30am PT",
      "Trial portal access being sent by Ken Nie",
      "Auth: TBD (not publicly documented; 6-fig license)",
      "Granola: https://notes.granola.ai/d/720db19c-06fb-4c7d-9eea-925e5fbb9526",
    ],
    overallStatus: "meeting-booked",
    commercialStatus: "wait",
    contacts: ["Rawley Dawson — rawley.dawson@cbinsights.com","Ken Nie — ken.nie@cbinsights.com","Nathan Lowery — nathan.lowery@cbinsights.com"],
    granolaLink: "https://notes.granola.ai/d/720db19c-06fb-4c7d-9eea-925e5fbb9526",
    pricing: "6-figure license + $0.01/data point; CEO approval required for all deals",
  },

  {
    id: "adbeat",
    name: "Adbeat",
    tier: "P1",
    category: "Advertising Intelligence",
    lastContactDate: "2026-04-02",
    emailStatus: "waiting-on-them",
    emailSubject: "Haley flagged $30-35K too high + shared calendar link Apr 2 — waiting for Porter to book",
    signal:
      "Display ad intelligence: programmatic, direct, native, pre-roll video. 35 countries. Strong for B2B display ad spend data. Real-time ad delivery data (500ms). NO search/social data. Full platform demo done Mar 26. Mar 31: Porter sent ballpark pricing ~$30-35K/yr. Apr 2: Haley replied — flagged $30-35K is too high for current scope, shared calendar link. Will cc'd. Waiting for Porter to book a follow-up call.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "adb-1", text: "Join rescheduled call with Porter on Thu Mar 26", owner: "me", done: true },
      { id: "adb-5", text: "Reply to Porter and schedule follow-up call to discuss pricing details + structure", owner: "me", done: true },
      { id: "adb-2", text: "Test in Clay — identify representative B2B customers who care about ad spend data", owner: "me", done: false },
      { id: "adb-3", text: "Receive API docs from Porter (still pending post-demo)", owner: "them", done: false },
      { id: "adb-4", text: "Schedule 30-min demo with Will", owner: "me", done: false },
    ],
    notes: [
      "Category: Advertising Intelligence — display ad coverage",
      "Mar 26: Full platform demo with Porter — walked through advertiser search, publisher profiles, keyword search, movers & shakers tool",
      "Haley asked about B2B SaaS use cases; Porter agreed Adbeat is strong for companies with ad spend signals",
      "Superior display ad coverage: programmatic, direct, native, pre-roll video",
      "35 countries; global coverage",
      "500ms real-time ad delivery data",
      "API: spend estimates, ad copy, network placement",
      "NOTE: NO search/social data — separate vendor needed for that",
      "Porter consulting Mark (VP Ops) on Clay-style partnership deal",
      "API docs promised post-call — still pending from Porter",
      "OEM/reseller pricing available; TBD",
      "Demo with Will still to schedule",
      "Granola: https://notes.granola.ai/d/a9aa8d7f-9452-4e96-8813-516a3c637928",
    ],
    overallStatus: "active",
    commercialStatus: "wait",
    contacts: ["Porter Bertanyi — porter@adbeat.com"],
    granolaLink: "https://notes.granola.ai/d/a9aa8d7f-9452-4e96-8813-516a3c637928",
    pricing: "$30-35K/yr est. depending on structure (ballpark from Porter Mar 31); API docs still pending",
  },

  {
    id: "dealroom",
    name: "Dealroom",
    tier: "P1",
    category: "Fundraising & Company Intelligence",
    lastContactDate: "2026-04-02",
    emailStatus: "none",
    signal:
      "Very strong EU coverage + strong US via city-level gov partnerships (Austin, Miami, Las Vegas). Funding + headcount + website traffic signals. Real-time/hourly refresh. Used by Clay + Apollo. Confirmed pricing: €12K/yr = 50K API calls (~$13-14K USD); €45K/yr = unlimited. Apr 2: Haley confirmed Thu Apr 9 at 9am PST with Miguel. Will to join.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "dr-1", text: "Create shared Slack channel (invite miguel.gustavosaa@dealroom.co)", owner: "me", done: true },
      { id: "dr-2", text: "Send eval questions to Miguel before Thu Mar 26 9am meeting", owner: "me", done: true },
      { id: "dr-3", text: "Join technical trial call Thu Mar 26 9:00 AM PT", owner: "me", done: true },
      { id: "dr-7", text: "Join Dealroom follow-up call Thu Apr 9 9:00am PST with Miguel (loop in Will)", owner: "me", done: false },
      { id: "dr-4", text: "Share eval doc with CTO / eng team (agreed on call)", owner: "me", done: false },
      { id: "dr-5", text: "Request 2-week trial API key from Kjeld Roos (API lead)", owner: "me", done: false },
      { id: "dr-6", text: "Await commercial follow-up from Will async", owner: "them", done: false },
    ],
    slackChannel: "#dealroom-unify",
    notes: [
      "Category: Fundraising & Company Intelligence",
      "Very strong EU coverage + US via city-level gov partnerships (Austin, Miami, Las Vegas)",
      "Funding rounds (all types + stage); headcount growth; website traffic",
      "People signals: founding team strength score; startup mafia tracking (PayPal/Uber alumni)",
      "Investor strength scoring",
      "Real-time/hourly refresh",
      "Used by Clay + Apollo — confirmed integrations",
      "White-label capability",
      "GDPR compliant",
      "Mar 26 call: Attended with Miguel + Kjeld Roos (API lead / technical contact)",
      "CONFIRMED PRICING: €12K/yr = 50K API calls (~$13–14K USD); €45K/yr = unlimited (Apollo model)",
      "Rate limits: 5 req/sec, 100 records/call → max 500 companies/sec",
      "Three data access models: API calls, data dump, custom integration",
      "2-week trial API key available — request from Kjeld",
      "Agreed: Haley to share eval doc with CTO/eng team; Will to follow up commercial async",
      "Contact: miguel.gustavosaa@dealroom.co | Kjeld Roos (API lead): kjeld@dealroom.co",
      "Granola: https://notes.granola.ai/d/95156b31-2543-4d74-9936-1dfd15cbff28",
    ],
    overallStatus: "active",
    commercialStatus: "wait",
    contacts: ["Matthieu Demolin — matthieu@dealroom.co","Miguel — miguel.gustavosaa@dealroom.co","Kjeld Roos (API lead) — kjeld@dealroom.co"],
    granolaLink: "https://notes.granola.ai/d/95156b31-2543-4d74-9936-1dfd15cbff28",
    pricing: "€12K/yr = 50K API calls (~$13–14K USD); €45K/yr = unlimited. 2-week trial available.",
  },

  {
    id: "seranking",
    name: "SE Ranking",
    tier: "P1",
    category: "Website Visitor · SEO · AI Visibility",
    lastContactDate: "2026-04-02",
    emailStatus: "needs-response",
    emailSubject: "Alex Trusevich sent API questionnaire + docs on Apr 2 — review and respond",
    signal:
      "AI search visibility scoring across all LLMs (ChatGPT, Claude, Perplexity) — very trendy signal. Organic traffic + PPC/ad spend parsed from Google SERP. US/Canada tier-1. Clay integration confirmed. Mar 31 call with Alex Trusevich (new contact, Accounts & API). Apr 2: Alex sent API questionnaire (partially pre-filled) + docs. Follow-up call booked Thu Apr 9 9:30-10am PDT.",
    hasApiKey: true,
    latencyTestRun: true,
    actionItems: [
      { id: "ser-1", text: "Receive API key + free trial credits from Roman", owner: "them", done: false },
      { id: "ser-2", text: "Roman to introduce to data PM + sales team", owner: "them", done: true },
      { id: "ser-5", text: "Review API questionnaire + docs sent by Alex Trusevich on Apr 2", owner: "me", done: false },
      { id: "ser-6", text: "Attend SE Ranking follow-up call Thu Apr 9 9:30-10am PDT with Alex Trusevich + Guifre Ballester", owner: "me", done: false },
      { id: "ser-3", text: "Review API pricing calculator at seranking.com/api/data/ai-search", owner: "me", done: false },
      { id: "ser-4", text: "Confirm rate limit window on paid plan (trial hits 429 after 1-3 requests — hard blocker)", owner: "me", done: false },
    ],
    notes: [
      "Category: Website Visitor, AI Search Visibility, SEO",
      "Trial account signed up Mar 25",
      "AI search visibility score: % of LLM queries company appears in (ChatGPT, Claude, Perplexity)",
      "Organic traffic + PPC/ad spend parsed from Google SERP",
      "US/Canada tier-1 data quality; Europe strong",
      "Clay integration confirmed",
      "Auth: API key (trial signup done)",
      "Rate limit (trial): ~1 req/sec; progressive throttle on violations",
      "Latency test results: Domain Overview 429 after 1-3 sequential requests — hard blocker",
      "Backlinks Summary: warm avg 421ms, cold avg 1,629ms (high cold/warm gap)",
      "Keyword Research: warm avg 1,448ms. Consistent. Burst errors under concurrent load.",
      "Rate limit: progressive throttle (10-min block, escalating) on violations",
      "Bulk: bulk data dump option available",
      "Pricing: credit-based per data type; pricing at seranking.com/api/data/ai-search",
      "Mar 31 call with Alex Trusevich (lex@seranking.com) and Guifre Ballester",
      "Follow-up call: Thu Apr 9 9:30-10am PDT",
      "Granola: https://notes.granola.ai/d/bac839b3-8484-4d1e-ae0c-dc7dc74a557f",
    ],
    overallStatus: "meeting-booked",
    commercialStatus: "wait",
    contacts: ["Roman Chygur — roman@seranking.com","Alex Trusevich — lex@seranking.com","Guifre Ballester — guifre.ballester@seranking.com"],
    slackChannel: "#unify-seranking",
    granolaLink: "https://notes.granola.ai/d/bac839b3-8484-4d1e-ae0c-dc7dc74a557f",
    pricing: "Credit-based; pricing at seranking.com/api/data/ai-search",
  },

  {
    id: "serpstat",
    name: "SerpStat",
    tier: "P1",
    category: "Tech Stack & Technographics · SEO",
    lastContactDate: "2026-04-03",
    emailStatus: "none",
    signal:
      "SEO analytics platform. 1.8M domains globally. Core signals: visibility/traffic estimates, 7B keywords, domain authority, backlinks, 1,200+ industry categories, ad spend tracking. Full DB dump: $9K one-time. JSON-RPC 2.0 (non-standard). Mar 30 meeting with Eugene + Will. Coverage eval: 64% overall (66/103); Pre-Series A only 29%; UK 45%, Germany 44%. Apr 3: Eugene sent updated coverage review (HTML + CSV with all available fields). Wants to catch up next week on pricing + wants a Unify demo. Sam Seiler added to channel.",
    hasApiKey: true,
    latencyTestRun: false,
    actionItems: [
      { id: "ss-1", text: "Review Serpstat & Unify.html doc from Eugene (attached to Mar 23 email + shared in Slack)", owner: "me", done: false },
      { id: "ss-2", text: "Join Mon Mar 30 10:00am PT meeting with Eugene (rescheduled from Mar 26)", owner: "me", done: true },
      { id: "ss-5", text: "Schedule call with Eugene next week to discuss pricing and updated coverage data (he requested Apr 3)", owner: "me", done: false },
      { id: "ss-3", text: "Send Eugene outstanding questions: pay-as-you-go vs $999/yr min, credits charged on no-results?, SOC2 cert, DPA availability, parent/child API key support, p50/p99 latency commitments", owner: "me", done: false },
      { id: "ss-4", text: "Address Pre-Series A coverage gap (29%) and UK/Germany weakness (44-45%) with Eugene", owner: "me", done: false },
    ],
    notes: [
      "First call Mar 20 with Eugene Romanuk",
      "Mar 30 meeting with Eugene + Will Stewart",
      "Category: Tech Stack & Technographics; SEO analytics",
      "1.8M domains globally tracked",
      "7B keywords tracked; domain authority; backlink analysis",
      "1,200+ industry categories (3-level hierarchy)",
      "Ad spend tracking",
      "Real-time traffic dynamics; domain rank trust score (>60 = high trust)",
      "Auth: Personal API token (from Serpstat profile section)",
      "Rate limits: 1 req/sec standard; up to 10 req/sec top-tier; max 60,000 rows/API method",
      "Coverage eval (Mar 30): 64% overall (66/103 companies); Pre-Series A 29%; Series C+ 95%; Bootstrapped 100%; UK 45%; Germany 44%",
      "Full DB dump: $9K one-time (all 1.8M domains)",
      "API: pay-as-you-go credit model + bulk enrichment (mid+top-tier plans only)",
      "Response format: JSON-RPC 2.0 (non-standard — factor into client lib selection!)",
      "On Clay: Semrush = 2 credits (cheapest); Serpstat = 5 credits; Lusha = 8 credits",
      "Granola (Mar 30): https://notes.granola.ai/d/c9684efa-2257-4d0a-852b-1aca658ff20d",
    ],
    overallStatus: "active",
    commercialStatus: "ready",
    contacts: ["Eugene Romanuk — e.romanuk@serpstat.co"],
    slackChannel: "#serpstat-unify",
    granolaLink: "https://notes.granola.ai/d/478e5c84-5f2d-42c8-90e6-ebb99b6e8c06",
    pricing: "Credit-based API; full DB dump $9K one-time (1.8M domains)",
  },

  {
    id: "crustdata",
    name: "CrustData",
    tier: "P1",
    category: "Company Data · People Data",
    lastContactDate: "2026-04-04",
    emailStatus: "needs-response",
    emailSubject: "Rohit following up Apr 4 — confirm if still interested in CrustData evaluation",
    signal:
      "YC-backed, closing Series A April. Built as search engine (not scraper) — real-time LinkedIn profile updates. 500M cached profiles, adding 1M/week. Sources: LinkedIn, Crunchbase, Google News, Gartner, Glassdoor, G2, ProductHunt, SimilarWeb, GitHub. $4K/mo = 40K credits. MCP server for Claude/OpenAI agents. Rohit sent pricing spreadsheet Mar 20. Apr 4: Rohit followed up asking if still interested — needs a reply.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "cd-1", text: "Receive pricing spreadsheet + technical docs from Rohit", owner: "them", done: true },
      { id: "cd-4", text: "Reply to Rohit's Apr 4 follow-up — confirm interest in CrustData evaluation", owner: "me", done: false },
      { id: "cd-2", text: "Review pricing sheet and decide on trial scope", owner: "me", done: false },
      { id: "cd-3", text: "Secure trial API credentials via Andrew Kim/Andres (Nov 2025 relationship)", owner: "me", done: false },
    ],
    notes: [
      "Met Mar 20 with Rohit Doshi + Saurabh",
      "YC-backed; closing Series A in April",
      "Built as search engine (NOT a scraper) — real-time LI profile updates",
      "500M cached profiles; adding 1M/week",
      "Data sources: LinkedIn, Crunchbase, Google News, Gartner, Glassdoor, G2, ProductHunt, SimilarWeb, GitHub",
      "Auth: TBD (API key expected)",
      "Pricing: $4K/month = 40K credits; cached = 100 cos/credit; real-time = 1 co/credit",
      "Full dataset: $20K/month ($240K annual)",
      "MCP server for Claude/OpenAI agents",
      "Clients: AI SDR, Luru, Artisan, Regie",
      "Trial builds on Nov 2025 relationship with Andrew Kim + Andres",
      "Rohit to send pricing spreadsheet + docs",
      "Granola: https://notes.granola.ai/d/e4dfecf2-36f0-419c-8fde-b31247661f17",
    ],
    overallStatus: "active",
    commercialStatus: "ready",
    contacts: ["Rohit Doshi — rohit.doshi@crustdata.co","Saurabh — saurabh@crustdata.co"],
    granolaLink: "https://notes.granola.ai/d/e4dfecf2-36f0-419c-8fde-b31247661f17",
    pricing: "$4K/mo=40K credits; cached=100cos/cr vs real-time=1co/cr; Full: $20K/mo",
  },

  {
    id: "upriver",
    name: "UpRiver",
    tier: "P1",
    category: "Social Intelligence · Advertising",
    lastContactDate: "2026-04-05",
    emailStatus: "needs-response",
    emailSubject: "Joe Tam checking in on eval — visit API playground at dashboard.upriver.ai",
    signal:
      "Only social intelligence vendor using YouTube sponsorship data to reveal brand audience targeting. Input: company domain → output: sponsorship activity, brand details, products. Creator engagement data (YouTube primary, Instagram secondary). API key provided. Mar 31: Joe Tam (eng) checked in on eval in #unify-upriver — offered to help, shared API playground (dashboard.upriver.ai) and skill.md for coding agents.",
    hasApiKey: true,
    latencyTestRun: false,
    actionItems: [
      { id: "ur-1", text: "Test the Upriver API using the key Lulu provided on Mar 24 (API playground: dashboard.upriver.ai)", owner: "me", done: false },
      { id: "ur-2", text: "Review sponsorship demo videos shared in #unify-upriver (SoFi, etc.)", owner: "me", done: false },
      { id: "ur-3", text: "Share more use case examples with Lulu/Joe so they can map endpoints", owner: "me", done: false },
    ],
    notes: [
      "Two calls: Mar 20 (first) + Mar 24 (follow-up demo with Lulu)",
      "Slack channel: #unify-upriver (created by Lulu Mar 24)",
      "API key provided via email Mar 24 (for testing)",
      "Pricing sheet sent Mar 20",
      "Demo videos shared in Slack: sponsorships/creators + emerging topics",
      "Mar 31: Joe Tam checked in on eval — offered API playground (dashboard.upriver.ai) + skill.md for agents",
      "Only social intelligence vendor using YouTube sponsorship data",
      "Input: company domain → sponsorship activity, brand details, products",
      "Creator endpoint: engagement data (YouTube primary, Instagram secondary)",
      "Natural language search for companies/creators",
      "Credit-based API ($0.08/credit base; different endpoints consume varying credits)",
      "Partner minimums $500–2K/month; annual contracts available; pilot period offered",
      "Clay integration confirmed",
      "API-native, built for agent workflows; supports column enrichment (Clay-style)",
      "Granola: https://notes.granola.ai/d/7a2f5455-2722-416e-988f-a4bacad7aaf0",
    ],
    overallStatus: "trial",
    commercialStatus: "ready",
    contacts: ["Lulu Zhang — lulu@upriver.ai","Joe Tam — joe@upriver.ai"],
    slackChannel: "#unify-upriver",
    granolaLink: "https://notes.granola.ai/d/7a2f5455-2722-416e-988f-a4bacad7aaf0",
    pricing: "$0.08/credit base; varies by endpoint; $500–2K/mo partner min",
  },

  // ── P2 ────────────────────────────────────────────────────────────────────

  {
    id: "spade",
    name: "Spade",
    tier: "P2",
    category: "Tech Stack · Payments · Ecommerce",
    lastContactDate: "2026-04-02",
    emailStatus: "needs-response",
    emailSubject: "Lily revised to mid-5-figures range — evaluate and respond",
    signal:
      "Merchant enrichment: payment signals, MCC codes, tech stack (Stripe, Shopify, etc.). 99.9% of payment-accepting merchants in NA. US + Canada only. Continuous refresh. NDA signed by Will. Apr 2: Haley pushed back on 6-figure minimum, shared volume estimates. Lily replied same day — revised pricing to 'mid 5 figures' range based on shared volumes. Haley hasn't responded yet to revised offer.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "sp-1", text: "NDA signed by Will ✓ — waiting on Will to respond to Lily with monthly volume estimate", owner: "will", done: true },
      { id: "sp-3", text: "Respond to Lily's revised mid-5-figures pricing — evaluate if range is acceptable vs 6-figure original", owner: "me", done: false },
      { id: "sp-2", text: "Once pricing/API docs received, run evaluation", owner: "me", done: false },
    ],
    notes: [
      "Category: Tech Stack & Technographics, Payments Data, Ecommerce",
      "99.9% of payment-accepting merchants in NA (US + Canada only)",
      "Merchant enrichment: payment signals, MCC codes, tech stack inference (Stripe, Shopify, etc.)",
      "Semantic category layer beyond MCC — key differentiator",
      "Continuous refresh; real-time REST API + batch support",
      "NDA required before API docs shared (Lily sending)",
      "Pricing: 6-figures/yr minimum (OEM not their core business)",
      "Only justifiable at similar scale to Clay agreement",
      "Per-API-call volume-based — expensive if minimum for niche data",
      "Auth: TBD (NDA first)",
      "Attention: https://app.attention.tech/conversations/a69851f6-a75e-43f7-b645-7488928b5647",
      "Granola: https://notes.granola.ai/d/ef80e7aa-4e6e-4669-b0ee-41a7627d0705",
    ],
    overallStatus: "blocked",
    commercialStatus: "blocked",
    contacts: ["Oban MacTavish — oban@spade.com","Lily Cohen — lily@spade.com"],
    attentionLink: "https://app.attention.tech/conversations/a69851f6-a75e-43f7-b645-7488928b5647",
    granolaLink: "https://notes.granola.ai/d/ef80e7aa-4e6e-4669-b0ee-41a7627d0705",
    pricing: "6-figures/yr minimum; per-API-call volume-based",
  },

  // ── DO NOT CONTACT ─────────────────────────────────────────────────────────

  {
    id: "vendelux",
    name: "Vendelux",
    tier: "P1",
    category: "Event Attendance Signals",
    lastContactDate: "2026-03-18",
    emailStatus: "none",
    signal:
      "Event attendee / intent data. Call was Mar 18. Flagged: DO NOT REACH OUT. All details TBD.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [],
    notes: [
      "Category: Event Attendance Signals",
      "Event attendee / intent data",
      "Call Mar 18 1:00pm PT",
      "Status: DO NOT REACH OUT (flagged in sheet)",
      "All data fields TBD",
    ],
    overallStatus: "do-not-contact",
    commercialStatus: null,
    contacts: [],
  },

  // ── MEETINGS DONE — FOLLOW UP NEEDED ──────────────────────────────────────

  {
    id: "companyenrich",
    name: "CompanyEnrich",
    tier: null,
    category: "Company Data",
    lastContactDate: "2026-03-23",
    emailStatus: "needs-response",
    emailSubject: "Follow up after intro call (Mon Mar 23 12pm with Amir)",
    signal:
      "Active trial. Call Mon Mar 23 12pm with Amir Nurmagomedov (amirali@companyenrich.com). Data partnership discussion. All technical details TBD — capture from call notes.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "ce-1", text: "Send follow-up email to Amir (amirali@companyenrich.com) with next steps from Mar 23 call", owner: "me", done: false },
      { id: "ce-2", text: "Fill in signal / pricing / API format details from call notes", owner: "me", done: false },
    ],
    notes: [
      "Call Mon Mar 23 12:00pm with Amir Nurmagomedov (amirali@companyenrich.com)",
      "Active trial / meeting done",
      "Data partnership: UnifyGTM <> CompanyEnrich",
      "All technical details TBD — pending review of call notes",
    ],
    overallStatus: "trial",
    commercialStatus: "ready",
    contacts: ["Amir Nurmagomedov — amirali@companyenrich.com"],
  },

  {
    id: "buyercaddy",
    name: "BuyerCaddy",
    tier: "P1",
    category: "Technographics · Tech Stack",
    lastContactDate: "2026-04-06",
    emailStatus: "needs-response",
    emailSubject: "Mitch sent partnership proposals — $12K=250K credits or $36K=2M credits; review and respond",
    signal:
      "Technographic data platform with 172K IT products, 92K vendors, 31.2M+ companies across 55 countries. G2 taxonomy, 10+ years of history, all data timestamped. Founded by former HG Insights founder (Craig Harris) + former Salesforce/Data.com CTO (Pawan Nachnani). Apr 3 meeting done with Craig, Mitch + Will. BuyerCaddy willing to build custom APIs exclusive to Unify. Mitch emailed pricing proposals: $12K=250K credits OR $36K=2M credits (both annual). Apr 6: Mitch confirmed pricing is for annual commitment and asked what they can work on this week.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "bc-3", text: "Attend BuyerCaddy meeting Fri Apr 3 10–10:45am PT with Craig Harris, Pawan Nachnani, Mitch Warren + Will", owner: "me", done: true },
      { id: "bc-1", text: "Review BuyerCaddy partnership notes + API reference in #buyercaddy-unify", owner: "me", done: false },
      { id: "bc-2", text: "Review pricing proposals from Mitch: $12K=250K credits or $36K=2M credits — decide on tier", owner: "me", done: false },
      { id: "bc-4", text: "Will to connect with Mitch next week for commercial discussion and finance questions", owner: "will", done: false },
    ],
    notes: [
      "Intro call Mon Mar 23 with Mitch Warren (Head of Sales)",
      "Slack channel: #buyercaddy-unify — Craig (CEO), Pawan (CTO), Mitch (Sales) all joined",
      "172K IT products | 92K vendors | 31.2M+ companies | 55 countries | 10+ years of history",
      "G2 taxonomy — customers know they're selecting the correct product",
      "All data timestamped: first verified, last verified, hit count",
      "Unique IP signals: benchmarking, IT spend, curated sales verbiage, churn data",
      "Founded by former HG Insights founder (Craig Harris, CEO) + former Salesforce/Data.com CTO (Pawan Nachnani)",
      "Data delivery: flat file, APIs, MCP Server",
      "API reference: buyercaddy-api.readme.io/reference/quick-start",
    ],
    overallStatus: "active",
    commercialStatus: "ready",
    contacts: ["Craig Harris (CEO) — craig@buyercaddy.com","Pawan Nachnani (CTO) — pawan@buyercaddy.com","Mitch Warren — mitch@buyercaddy.com"],
    slackChannel: "#buyercaddy-unify",
    granolaLink: "https://notes.granola.ai/d/db8ff6cb-5e9e-485f-ab30-8d278d5b4994",
    pricing: "Starter: $12K=250K credits; Growth: $36K=2M credits (custom flat-fee option <$100K also TBD)",
  },

  {
    id: "hithorizons",
    name: "HitHorizons",
    tier: "P1",
    category: "Company Data · European Coverage",
    lastContactDate: "2026-04-02",
    emailStatus: "needs-response",
    emailSubject: "Tibor wants Teams call next week to activate trial (Easter Fri-Mon Apr 3-6)",
    signal:
      "European company database — 80M+ companies across Europe (Slovakia-based via FinStat). US data also deliverable. API pricing: €3,500/60K calls (€0.058/call) to €33K/6M calls. Bulk data €220K/yr for all Europe. 10-day free trial available (300 calls/day). Tibor emailed Apr 2 — Easter holidays Fri-Mon (Apr 3-6); wants Teams call week of Apr 7 to activate trial.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "hh-1", text: "Reply to Tibor — confirm Teams call next week to activate trial (or reply with trial info: email, start/end dates, feedback call time)", owner: "me", done: false },
      { id: "hh-2", text: "Review HitHorizons API docs + sample export (Sweden sample attached to email)", owner: "me", done: false },
    ],
    notes: [
      "Met Mar 23 with Tibor Jánoška (Key Account Manager)",
      "Tibor sent full pricing + API docs + sample export on Mar 24",
      "Category: European company data — 80M+ companies",
      "Countries: all of Europe; US data available; rest-of-world calculable",
      "Bulk data: €220K/yr for all Europe; pricing varies by contract length, attributes, update frequency",
      "API pricing: €3,500 advance = 60K calls (€0.058/call) | €6K = 120K | €9K = 250K | €12.5K = 600K | €33K = 6M calls",
      "10-day free trial: 300 API calls/day — requires email, dates, and feedback call to activate",
      "Docs: HitHorizons Partner API Documentation (PDF attached)",
      "Contact: tibor.janoska@hithorizons.com | +421 940 992 732",
    ],
    overallStatus: "active",
    commercialStatus: null,
    contacts: ["Tibor Jánoška — tibor.janoska@hithorizons.com"],
    pricing: "API: €3.5K/60K calls → €33K/6M calls; Bulk EU: €220K/yr",
  },

  {
    id: "theirstack",
    name: "TheirStack",
    tier: null,
    category: "Tech Stack · Job Posting Signals",
    lastContactDate: "2026-03-24",
    emailStatus: "needs-response",
    emailSubject: "Follow up after intro call (Tue Mar 24 12pm)",
    signal:
      "Intro call Tue Mar 24 12:00pm with Xoel López + Christian (christian@theirstack.com, xoel@theirstack.com). All details TBD — capture from call notes.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "tst-1", text: "Send follow-up email to Xoel + Christian with next steps from Mar 24 call", owner: "me", done: false },
      { id: "tst-2", text: "Fill in vendor details from call notes", owner: "me", done: false },
    ],
    notes: [
      "Call Tue Mar 24 12:00pm with Xoel López + Christian",
      "Contact: christian@theirstack.com, xoel@theirstack.com",
      "All details TBD",
    ],
    overallStatus: "active",
    commercialStatus: null,
    contacts: ["Xoel López — xoel@theirstack.com","Christian — christian@theirstack.com"],
  },

  {
    id: "pitchbook",
    name: "PitchBook",
    tier: "P0",
    category: "Fundraising & Company Intelligence",
    lastContactDate: "2026-03-26",
    emailStatus: "waiting-on-them",
    emailSubject: "Shouyi to send pricing table; too expensive for current stage",
    signal:
      "Fundraising & company intelligence. Mar 26 call with Shouyi Poon: $160K/yr minimum for 1,000 end users (data licensing model). Requires end-users to be PitchBook licensees — access gated by SSO. No formal Clay partnership (just a marketplace listing). Pricing scales to ~$5–6K/user at 10K users. No trial available. Budget too high for current stage — deprioritized until we scale. Shouyi to send pricing table.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "pb-1", text: "Attend meeting with Shouyi Poon (partnerships team) on Thu Mar 26", owner: "me", done: true },
      { id: "pb-2", text: "Receive pricing table from Shouyi Poon", owner: "them", done: false },
      { id: "pb-3", text: "Revisit when Unify scales to larger user base (too expensive now at $160K/yr min)", owner: "me", done: false },
    ],
    notes: [
      "Mar 26 call with Shouyi Poon (partnerships team)",
      "BLOCKER: $160K/yr minimum for 1,000 end users — licensing model, not API-first",
      "Requires end-users to be existing PitchBook licensees (SSO-gated access) — fundamentally different from Clay model",
      "No formal Clay partnership — Clay is just listed on PitchBook marketplace; no data redistribution deal",
      "Pricing scales: $160K/yr at 1K users → ~$5–6K/user at 10K users",
      "No trial available (licensing model requires contract)",
      "Haley said: budget too high for current stage",
      "Shouyi to send pricing table async",
      "Category: Fundraising & Company Intelligence (funding rounds, ownership, investor signals)",
      "Use cases: filter by funding stage, enrich accounts with financials, trigger outbound on new rounds",
      "Ellie Desler flagged previously: strict data redistribution guidelines — confirmed on call",
    ],
    overallStatus: "active",
    commercialStatus: "blocked",
    contacts: ["Shouyi Poon (partnerships) — shouyi.poon@pitchbook.com","Ellie Desler (sales) — ellie.desler@pitchbook.com"],
  },

  {
    id: "hginsights",
    name: "HG Insights",
    tier: null,
    category: "Tech Intelligence",
    lastContactDate: "2026-03-24",
    emailStatus: "needs-response",
    emailSubject: "Follow up after intro call (Tue Mar 24 2pm)",
    signal:
      "Intro call Tue Mar 24 2:00pm with Ed Field (ed.field@hginsights.com). Tech intelligence data. Env var: HGINSIGHTS_KEY. All details TBD — capture from call notes.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "hgi-1", text: "Send follow-up email to Ed Field with next steps from Mar 24 call", owner: "me", done: false },
      { id: "hgi-2", text: "Fill in signal / pricing / API format details from call notes", owner: "me", done: false },
      { id: "hgi-3", text: "Get API key (env var: HGINSIGHTS_KEY) and run smoke test", owner: "me", done: false },
    ],
    notes: [
      "Call Tue Mar 24 2:00pm with Ed Field",
      "Contact: ed.field@hginsights.com",
      "Category: P1 Enrichment — tech intelligence",
      "Env var needed: HGINSIGHTS_KEY",
      "Endpoints to test: Tech Intelligence",
      "All details TBD from call notes",
    ],
    overallStatus: "active",
    commercialStatus: null,
    contacts: ["Ed Field — ed.field@hginsights.com"],
  },

  // ── UPCOMING MEETINGS ────────────────────────────────────────────────────────

  {
    id: "dealfront",
    name: "Dealfront",
    tier: null,
    category: "Website Visitor · Company Intelligence",
    lastContactDate: null,
    emailStatus: "none",
    signal:
      "Meeting still rescheduling. Original meeting Mar 27 no-show; rescheduled to Mar 31 but wrong time booked. Apr 1: Matthew apologized + offered to reschedule. Haley asked for 9:30am PT slot Apr 2 or 3. Waiting for confirmation. Note: Matthew's actual email is matthew.fairey@leadfeeder.com.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "df-1", text: "Reschedule meeting with Matthew Fairey — Haley asked for 9:30am PT; waiting for confirmation", owner: "them", done: false },
    ],
    notes: [
      "Meeting still being rescheduled — original Mar 27 9am PDT, then Mar 31 2pm (wrong timezone), still pending",
      "Contact: Matthew Fairey (matthew.fairey@leadfeeder.com) — NOT dealfront.com",
      "No prior contact; category TBD",
      "All details TBD",
    ],
    overallStatus: "meeting-booked",
    commercialStatus: null,
    contacts: ["Matthew Fairey — matthew.fairey@leadfeeder.com"],
    lastContactDate: "2026-04-01",
    emailStatus: "waiting-on-them",
  },

  // ── DEPRIORITIZED ────────────────────────────────────────────────────────────

  {
    id: "retentiondotcom",
    name: "Retention.com",
    tier: "P1",
    category: "Website Visitor",
    lastContactDate: null,
    emailStatus: "none",
    signal:
      "Website visitor de-anonymization. OEM: $0.08/resolution + $1.00/domain fee. Volume tiers: $0.06 at 50K, $0.05 at 100K+. Similar to RB2B. Deprioritized — skip for now. Would serve more as a waterfall on existing web intent.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [],
    notes: [
      "Deprioritized — skip for now per commercial brief",
      "Similar to RB2B; would serve as waterfall on existing web intent",
      "OEM: $0.08/resolution + $1.00/domain fee",
      "Volume tiers: $0.06 at 50K resolutions; $0.05 at 100K+",
      "Usage-based, no prepaid credits",
      "Contact: Robb Clarke — robb@retention.com; Kaley — kaley@retention.com",
      "No company finder — website visitor ID/de-anonymization only",
    ],
    overallStatus: "do-not-contact",
    commercialStatus: "blocked",
    contacts: ["Robb Clarke — robb@retention.com", "Kaley — kaley@retention.com"],
    pricing: "$0.08/resolution + $1.00/domain; $0.06 at 50K+; $0.05 at 100K+",
  },

  {
    id: "builtwith",
    name: "BuiltWith",
    tier: "P1",
    category: "Technographics · Tech Stack",
    lastContactDate: "2026-03-24",
    emailStatus: "none",
    signal:
      "Tech stack detection via Domain API. Gary Brewer (founder) confirmed Clay uses the standard public Domain API — no special partnership required. Volume discounts available at >1M API credits. Straightforward pay-as-you-go model.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "bw-1", text: "Evaluate Domain API coverage and pricing tiers for our volume", owner: "me", done: false },
      { id: "bw-2", text: "Compare vs BuyerCaddy for technographics coverage", owner: "me", done: false },
    ],
    notes: [
      "Category: Technographics — tech stack detection",
      "Core product: Domain API (tech stack per domain)",
      "Gary Brewer confirmed Clay uses standard public Domain API — no OEM/partnership deal",
      "Volume discounts kick in at >1M API credits",
      "Email Mar 24: 'For sure they just pay for the Domain API like everyone else - however we can offer discounts if you buy more than 1,000,000 API credits.'",
      "Contact: Gary Brewer — support@builtwith.com",
    ],
    overallStatus: "active",
    commercialStatus: "wait",
    contacts: ["Gary Brewer — support@builtwith.com"],
    pricing: "Pay-as-you-go credits; volume discount at >1M credits",
  },

  // ── NEW FROM SWEEP ────────────────────────────────────────────────────────────

  {
    id: "perigon",
    name: "Perigon",
    tier: null,
    category: "News & Media Intelligence",
    lastContactDate: "2026-04-03",
    emailStatus: "waiting-on-them",
    emailSubject: "Haley submitted sales inquiry Apr 3 — awaiting response from Perigon team",
    signal:
      "News API. Mar 26 meeting with Jeff (jeff@perigon.io). Real-time news + media monitoring. Apr 3: Haley submitted sales inquiry — auto-reply received, awaiting response from team.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "peri-1", text: "Fill in signal / pricing / API format details from Mar 26 call notes", owner: "me", done: false },
      { id: "peri-2", text: "Evaluate for news signal use cases in Unify", owner: "me", done: false },
    ],
    notes: [
      "First meeting: Mar 26 with Jeff (jeff@perigon.io)",
      "Category: News & Media Intelligence",
      "All details TBD — capture from call notes",
    ],
    overallStatus: "active",
    commercialStatus: null,
    contacts: ["Jeff — jeff@perigon.io"],
  },

  {
    id: "newscatcher",
    name: "NewsCatcher API",
    tier: null,
    category: "News & Media Intelligence",
    lastContactDate: "2026-04-03",
    emailStatus: "needs-response",
    emailSubject: "Dima asked if Unify is YC — offering reduced rate (Apr 3); respond with decision",
    signal:
      "High-recall news search API. Two delivery modes: (1) data dump — send list of entities, receive pre-clustered/deduped articles about them (scalable to 1M+ names); (2) signal search API — broad natural language query, returns enriched events with company names extracted (~10–15 min, highest industry recall). NOT real-time. Pricing: $60–80K/yr minimum upfront. Apr 2: Haley pushed back on $60K minimum. Apr 3: Dima replied asking if Unify is YC — says no dedicated floors for YC companies + reduced rate available.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "nc-1", text: "Receive 'bank of queries' + sample data file + pricing from Dima", owner: "them", done: false },
      { id: "nc-4", text: "Reply to Dima — confirm if Unify is YC and whether reduced rate is sufficient to proceed", owner: "me", done: false },
      { id: "nc-2", text: "Review sample data and assess fit for Unify's news signal use cases", owner: "me", done: false },
      { id: "nc-3", text: "Evaluate vs Perigon — $60–80K/yr is high; assess if recall advantage justifies cost", owner: "me", done: false },
    ],
    notes: [
      "Mar 27 call with Dima Grama (dima@newscatcherapi.com)",
      "Category: News & Media Intelligence — high recall focus",
      "Two delivery modes: (1) data dump (entity list → clustered articles), (2) signal search (query → events + company enrichment)",
      "Signal search: ~10–15 min per query — NOT suitable for on-demand / real-time user queries",
      "Light search version: ~1 min but no enrichments (record titles + citations only, no company names)",
      "Enrichments in full mode: company names, event details, categories extracted via LLM pre-validation",
      "Benchmarked highest recall vs OpenAI deep search, Perplexity, Google, Parallel, Tabili",
      "Suggested use: batch/recurring (daily/weekly) — not live query",
      "Free trial: 2K credits, 1 concurrent job",
      "Pricing: $60–80K/yr minimum upfront — high commitment relative to other news vendors",
      "Dima will send 'bank of queries' (categorized signals with suggested cadences) + sample demo file",
      "Haley to send B2B SaaS signal examples / Unify customer case studies as context",
      "Redistribution terms: TBD — needs discussion",
    ],
    overallStatus: "active",
    commercialStatus: "wait",
    contacts: ["Dima Grama — dima@newscatcherapi.com"],
  },

  {
    id: "trigify",
    name: "Trigify",
    tier: null,
    category: "Social Listening · Intent Signals",
    lastContactDate: "2026-04-01",
    emailStatus: "waiting-on-them",
    emailSubject: "Haley sent Slack invite to Max Apr 1 — waiting for him to join and share API key + pricing",
    signal:
      "Social signal intelligence: LinkedIn, X, Reddit, YouTube, podcasts, TikTok, GitHub, HackerNews. Key signals: topic-based engagement search (who's engaging with keywords/topics/competitors), boolean queries. Two key endpoints: Social Topics (live, what Clay uses) + Social Mapping (database). Clay integration live. Mar 27 call with Max Mitcham. Apr 1: Haley sent Slack invite to Max. Waiting for Max to join and activate account.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "tri-1", text: "Reply to Max's email — confirm account activation and request to set up Slack channel", owner: "me", done: true },
      { id: "tri-4", text: "Receive API test key + pricing tiers from Max once Slack is set up", owner: "them", done: false },
      { id: "tri-2", text: "Test Social Topics endpoint — run keyword searches (e.g. 'Unify', 'AI SDR', competitor names)", owner: "me", done: false },
      { id: "tri-3", text: "Evaluate usage-based vs annual commitment pricing; decide on structure", owner: "me", done: false },
    ],
    notes: [
      "Mar 27 call with Max Mitcham (max@trigify.io)",
      "Category: Social Listening, Intent Signals",
      "Monitors: LinkedIn, X, Reddit, YouTube, podcasts, TikTok, GitHub, HackerNews",
      "Social Topics endpoint (live): topic/keyword → people engaging with it (LinkedIn #1, X also supported)",
      "Social Mapping endpoint (database): faster, pre-indexed",
      "Boolean queries supported (AND/OR/NOT operators, job title filters)",
      "Can search by topic OR by specific profile (monitor who engages with competitor accounts)",
      "Enrichment chain: X profile → personal email → LinkedIn profile (reverse lookup)",
      "LinkedIn data: can't filter at source (filter post-fetch), other platforms more flexible",
      "Haley noted gap today: keywords/competitor monitoring not supported by Unify's current LinkedIn signals",
      "Clay uses Social Topics endpoint — same integration model available to Unify",
      "Pricing: usage-based (higher per-credit cost) OR tiered annual commitment; tiers to be shared by Max",
      "Partnership: Unify incurs credits on behalf of customers (same as Clay model)",
      "Timeline: Haley wants contracts in ~3–4 weeks",
      "Max sent API docs in chat during call",
    ],
    overallStatus: "active",
    commercialStatus: "wait",
    contacts: ["Max Mitcham — max@trigify.io"],
  },

  {
    id: "diffbot",
    name: "Diffbot",
    tier: null,
    category: "News & Media Intelligence · Knowledge Graph",
    lastContactDate: "2026-04-01",
    emailStatus: "needs-response",
    emailSubject: "Ben followed up Apr 1 asking about next steps — send standard API eval questionnaire",
    signal:
      "Knowledge graph built from scraping 300M+ global organizations + 100K+ news sources daily. News monitoring via article search: filter by entity, keyword, sentiment, publisher, language, date. Named entity recognition (NER) links companies/people in articles to firm profiles. To get domain from article: 2 API calls (25 + 25 credits). Public data only — redistribution allowed. Pricing: $299/mo = 10K entities, $899/mo = 40K entities. Demo done Mar 30 with Ben. Apr 1: Ben followed up checking in, asking if next steps needed.",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "dbt-1", text: "Attend first demo Mon Mar 30", owner: "me", done: true },
      { id: "dbt-2", text: "Send standard API eval questionnaire to Ben (ben@diffbot.com)", owner: "me", done: false },
      { id: "dbt-3", text: "Evaluate startup plan ($299/mo = 10K entities) as starting point for testing", owner: "me", done: false },
      { id: "dbt-4", text: "Assess 2-API-call flow for news → company domain extraction (latency implications)", owner: "me", done: false },
    ],
    notes: [
      "Mar 30 demo with Ben (ben@diffbot.com) — based Portland, OR; HQ Menlo Park",
      "Category: News Monitoring, Knowledge Graph, Web Extraction",
      "300M+ global organizations; 100K+ news sources scraped daily",
      "News freshness: every few hours for major outlets (Reuters, TechCrunch); up to 24hrs for niche sites",
      "Article search: filter by entity, keyword, sentiment score, publisher country/language, date",
      "NER: tags company/person/location entities per article with salience score + sentiment",
      "To extract company domain from article: (1) fetch article (25 credits) → (2) fetch org profile (25 credits) → get homepageUri",
      "25 credits per entity (article, person, or organization record)",
      "Pricing: $299/mo = 250K credits = ~10K entities; $899/mo = 1M credits = ~40K entities",
      "Credits expire monthly on standard plans; enterprise volume deals available at lower per-credit cost",
      "Redistribution allowed — only public data, no restrictions on repackaging for clients",
      "Bulk extraction (up to 100K specific URLs) + crawl available on higher tiers",
      "Knowledge graph recommended over custom crawl for news monitoring (pre-scaled, better freshness)",
      "Status page for API uptime available; latency low since data is static/pre-indexed",
      "Haley to start on $299/mo startup plan; revisit enterprise pricing if volume warrants",
    ],
    overallStatus: "active",
    commercialStatus: "wait",
    contacts: ["Ben — ben@diffbot.com"],
  },

  {
    id: "semrush",
    name: "Semrush",
    tier: null,
    category: "SEO · Competitive Intelligence",
    lastContactDate: "2026-04-02",
    emailStatus: "none",
    signal:
      "SEO + competitive intelligence platform (acquired by Adobe). Inbound partnership interest. Mar 31 call done with Erin Cook + Michael Dellamura. Key outcomes: 6-figure annual minimum; Adobe acquisition requires leadership approval + risk assessment for new partnerships. Apr 2: Haley emailed Erin/Michael — CEO can't commit to 6-figure minimum. Follow-up call still on calendar: Tue Apr 7 12:30–1pm PDT (may use to formally close out or explore alternatives).",
    hasApiKey: false,
    latencyTestRun: false,
    actionItems: [
      { id: "sem-1", text: "Attend partnership call Tue Mar 31 11:30am–12pm PT with Erin Cook + Michael Dellamura", owner: "me", done: true },
      { id: "sem-5", text: "Attend Semrush follow-up call Tue Apr 7 12:30–1pm PDT with Erin Cook + Michael Dellamura", owner: "me", done: false },
      { id: "sem-2", text: "Discuss 6-figure annual minimum with finance team", owner: "me", done: false },
      { id: "sem-3", text: "Prepare demo / workflow presentation to Semrush team", owner: "me", done: false },
      { id: "sem-4", text: "Submit exec summary to Semrush leadership (required due to Adobe acquisition)", owner: "me", done: false },
    ],
    notes: [
      "Inbound: Erin Cook (erin.cook@semrush.com) reached out Mar 30 re: partnership",
      "Mar 31 call: Erin Cook (AE) + Michael Dellamura — done",
      "Category: SEO, Competitive Intelligence",
      "6-figure annual minimum confirmed",
      "Adobe acquisition: requires leadership approval + risk assessment for all new partnerships",
      "Phase 1 APIs recommended: traffic & engagement (domain level), backlinks w/ Authority Score (0-100) + fraud detection, AI visibility / brand overview with share of voice",
      "Michael positioned as 'best in class, fast, cheap — pick two'",
      "Follow-up call: Tue Apr 7 12:30–1pm PDT",
    ],
    overallStatus: "active",
    commercialStatus: "wait",
    contacts: ["Erin Cook — erin.cook@semrush.com", "Michael Dellamura — michael.dellamura@semrush.com"],
    granolaLink: "https://notes.granola.ai/d/cb579e82-e999-4668-b39a-c6b54f603ab1",
  },
]
